//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegrationZetaPrueba2.EXPWSArticulos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="LIBRA", ConfigurationName="EXPWSArticulos.ExpWSArticulosSoapPort")]
    public interface ExpWSArticulosSoapPort {
        
        [System.ServiceModel.OperationContractAttribute(Action="LIBRAaction/AEXPWSARTICULOS.Execute", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        global::IntegrationZetaPrueba2.EXPWSArticulos.ExecuteResponse Execute(global::IntegrationZetaPrueba2.EXPWSArticulos.ExecuteRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="LIBRAaction/AEXPWSARTICULOS.Execute", ReplyAction="*")]
        System.Threading.Tasks.Task<global::IntegrationZetaPrueba2.EXPWSArticulos.ExecuteResponse> ExecuteAsync(global::IntegrationZetaPrueba2.EXPWSArticulos.ExecuteRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="ArticulosSDT.ArticuloItem", Namespace="LIBRA")]
    public partial class ArticulosSDTArticuloItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string nombreField;
        
        private string abreviacionField;
        
        private string codigoCategoriaField;
        
        private string codigoFamiliaField;
        
        private string codigoMarcaField;
        
        private string codigoProveedorField;
        
        private sbyte codigoIVAField;
        
        private string cuentaComprasField;
        
        private string cuentaVentasField;
        
        private string cuentaProduccionField;
        
        private string codigoOrigenField;
        
        private string codigoUnidadField;
        
        private string webField;
        
        private string codigoTextoField;
        
        private string notasField;
        
        private string activoField;
        
        private string listaDePreciosField;
        
        private string usaStockField;
        
        private string usaLotesField;
        
        private string usaVencimientosField;
        
        private sbyte codigoMonedaCostosField;
        
        private string fechaCostoField;
        
        private double costoField;
        
        private double porcentajeUtilidadField;
        
        /// <remarks/>
        public string Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("Codigo");
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <remarks/>
        public string Abreviacion {
            get {
                return this.abreviacionField;
            }
            set {
                this.abreviacionField = value;
                this.RaisePropertyChanged("Abreviacion");
            }
        }
        
        /// <remarks/>
        public string CodigoCategoria {
            get {
                return this.codigoCategoriaField;
            }
            set {
                this.codigoCategoriaField = value;
                this.RaisePropertyChanged("CodigoCategoria");
            }
        }
        
        /// <remarks/>
        public string CodigoFamilia {
            get {
                return this.codigoFamiliaField;
            }
            set {
                this.codigoFamiliaField = value;
                this.RaisePropertyChanged("CodigoFamilia");
            }
        }
        
        /// <remarks/>
        public string CodigoMarca {
            get {
                return this.codigoMarcaField;
            }
            set {
                this.codigoMarcaField = value;
                this.RaisePropertyChanged("CodigoMarca");
            }
        }
        
        /// <remarks/>
        public string CodigoProveedor {
            get {
                return this.codigoProveedorField;
            }
            set {
                this.codigoProveedorField = value;
                this.RaisePropertyChanged("CodigoProveedor");
            }
        }
        
        /// <remarks/>
        public sbyte CodigoIVA {
            get {
                return this.codigoIVAField;
            }
            set {
                this.codigoIVAField = value;
                this.RaisePropertyChanged("CodigoIVA");
            }
        }
        
        /// <remarks/>
        public string CuentaCompras {
            get {
                return this.cuentaComprasField;
            }
            set {
                this.cuentaComprasField = value;
                this.RaisePropertyChanged("CuentaCompras");
            }
        }
        
        /// <remarks/>
        public string CuentaVentas {
            get {
                return this.cuentaVentasField;
            }
            set {
                this.cuentaVentasField = value;
                this.RaisePropertyChanged("CuentaVentas");
            }
        }
        
        /// <remarks/>
        public string CuentaProduccion {
            get {
                return this.cuentaProduccionField;
            }
            set {
                this.cuentaProduccionField = value;
                this.RaisePropertyChanged("CuentaProduccion");
            }
        }
        
        /// <remarks/>
        public string CodigoOrigen {
            get {
                return this.codigoOrigenField;
            }
            set {
                this.codigoOrigenField = value;
                this.RaisePropertyChanged("CodigoOrigen");
            }
        }
        
        /// <remarks/>
        public string CodigoUnidad {
            get {
                return this.codigoUnidadField;
            }
            set {
                this.codigoUnidadField = value;
                this.RaisePropertyChanged("CodigoUnidad");
            }
        }
        
        /// <remarks/>
        public string Web {
            get {
                return this.webField;
            }
            set {
                this.webField = value;
                this.RaisePropertyChanged("Web");
            }
        }
        
        /// <remarks/>
        public string CodigoTexto {
            get {
                return this.codigoTextoField;
            }
            set {
                this.codigoTextoField = value;
                this.RaisePropertyChanged("CodigoTexto");
            }
        }
        
        /// <remarks/>
        public string Notas {
            get {
                return this.notasField;
            }
            set {
                this.notasField = value;
                this.RaisePropertyChanged("Notas");
            }
        }
        
        /// <remarks/>
        public string Activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("Activo");
            }
        }
        
        /// <remarks/>
        public string ListaDePrecios {
            get {
                return this.listaDePreciosField;
            }
            set {
                this.listaDePreciosField = value;
                this.RaisePropertyChanged("ListaDePrecios");
            }
        }
        
        /// <remarks/>
        public string UsaStock {
            get {
                return this.usaStockField;
            }
            set {
                this.usaStockField = value;
                this.RaisePropertyChanged("UsaStock");
            }
        }
        
        /// <remarks/>
        public string UsaLotes {
            get {
                return this.usaLotesField;
            }
            set {
                this.usaLotesField = value;
                this.RaisePropertyChanged("UsaLotes");
            }
        }
        
        /// <remarks/>
        public string UsaVencimientos {
            get {
                return this.usaVencimientosField;
            }
            set {
                this.usaVencimientosField = value;
                this.RaisePropertyChanged("UsaVencimientos");
            }
        }
        
        /// <remarks/>
        public sbyte CodigoMonedaCostos {
            get {
                return this.codigoMonedaCostosField;
            }
            set {
                this.codigoMonedaCostosField = value;
                this.RaisePropertyChanged("CodigoMonedaCostos");
            }
        }
        
        /// <remarks/>
        public string FechaCosto {
            get {
                return this.fechaCostoField;
            }
            set {
                this.fechaCostoField = value;
                this.RaisePropertyChanged("FechaCosto");
            }
        }
        
        /// <remarks/>
        public double Costo {
            get {
                return this.costoField;
            }
            set {
                this.costoField = value;
                this.RaisePropertyChanged("Costo");
            }
        }
        
        /// <remarks/>
        public double PorcentajeUtilidad {
            get {
                return this.porcentajeUtilidadField;
            }
            set {
                this.porcentajeUtilidadField = value;
                this.RaisePropertyChanged("PorcentajeUtilidad");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExpWSArticulos.Execute", WrapperNamespace="LIBRA", IsWrapped=true)]
    public partial class ExecuteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="LIBRA", Order=0)]
        public string Empid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="LIBRA", Order=1)]
        public string Emppassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="LIBRA", Order=2)]
        public string Codigo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="LIBRA", Order=3)]
        public int Inciar;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="LIBRA", Order=4)]
        public int Cantidad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="LIBRA", Order=5)]
        public string Fechaini;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="LIBRA", Order=6)]
        public string Fechafin;
        
        public ExecuteRequest() {
        }
        
        public ExecuteRequest(string Empid, string Emppassword, string Codigo, int Inciar, int Cantidad, string Fechaini, string Fechafin) {
            this.Empid = Empid;
            this.Emppassword = Emppassword;
            this.Codigo = Codigo;
            this.Inciar = Inciar;
            this.Cantidad = Cantidad;
            this.Fechaini = Fechaini;
            this.Fechafin = Fechafin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExpWSArticulos.ExecuteResponse", WrapperNamespace="LIBRA", IsWrapped=true)]
    public partial class ExecuteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="LIBRA", Order=0)]
        public sbyte Ok;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="LIBRA", Order=1)]
        public string Error;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="LIBRA", Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public IntegrationZetaPrueba2.EXPWSArticulos.ArticulosSDTArticuloItem[] Articulos;
        
        public ExecuteResponse() {
        }
        
        public ExecuteResponse(sbyte Ok, string Error, IntegrationZetaPrueba2.EXPWSArticulos.ArticulosSDTArticuloItem[] Articulos) {
            this.Ok = Ok;
            this.Error = Error;
            this.Articulos = Articulos;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ExpWSArticulosSoapPortChannel : global::IntegrationZetaPrueba2.EXPWSArticulos.ExpWSArticulosSoapPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExpWSArticulosSoapPortClient : System.ServiceModel.ClientBase<global::IntegrationZetaPrueba2.EXPWSArticulos.ExpWSArticulosSoapPort>, global::IntegrationZetaPrueba2.EXPWSArticulos.ExpWSArticulosSoapPort {
        
        public ExpWSArticulosSoapPortClient() {
        }
        
        public ExpWSArticulosSoapPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExpWSArticulosSoapPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExpWSArticulosSoapPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExpWSArticulosSoapPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        global::IntegrationZetaPrueba2.EXPWSArticulos.ExecuteResponse global::IntegrationZetaPrueba2.EXPWSArticulos.ExpWSArticulosSoapPort.Execute(global::IntegrationZetaPrueba2.EXPWSArticulos.ExecuteRequest request) {
            return base.Channel.Execute(request);
        }
        
        public sbyte Execute(string Empid, string Emppassword, string Codigo, int Inciar, int Cantidad, string Fechaini, string Fechafin, out string Error, out IntegrationZetaPrueba2.EXPWSArticulos.ArticulosSDTArticuloItem[] Articulos) {
            global::IntegrationZetaPrueba2.EXPWSArticulos.ExecuteRequest inValue = new global::IntegrationZetaPrueba2.EXPWSArticulos.ExecuteRequest();
            inValue.Empid = Empid;
            inValue.Emppassword = Emppassword;
            inValue.Codigo = Codigo;
            inValue.Inciar = Inciar;
            inValue.Cantidad = Cantidad;
            inValue.Fechaini = Fechaini;
            inValue.Fechafin = Fechafin;
            global::IntegrationZetaPrueba2.EXPWSArticulos.ExecuteResponse retVal = ((global::IntegrationZetaPrueba2.EXPWSArticulos.ExpWSArticulosSoapPort)(this)).Execute(inValue);
            Error = retVal.Error;
            Articulos = retVal.Articulos;
            return retVal.Ok;
        }
        
        public System.Threading.Tasks.Task<global::IntegrationZetaPrueba2.EXPWSArticulos.ExecuteResponse> ExecuteAsync(global::IntegrationZetaPrueba2.EXPWSArticulos.ExecuteRequest request) {
            return base.Channel.ExecuteAsync(request);
        }
    }
}
