'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.17626
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace IMPWSCliente
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="LIBRA", ConfigurationName:="IMPWSCliente.ImpWSClienteSoapPort")>  _
    Public Interface ImpWSClienteSoapPort
        
        <System.ServiceModel.OperationContractAttribute(Action:="LIBRAaction/AIMPWSCLIENTE.Execute", ReplyAction:="*")>  _
        Function Execute(ByVal request As IMPWSCliente.ExecuteRequest) As IMPWSCliente.ExecuteResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="LIBRAaction/AIMPWSCLIENTE.Execute", ReplyAction:="*")>  _
        Function ExecuteAsync(ByVal request As IMPWSCliente.ExecuteRequest) As System.Threading.Tasks.Task(Of IMPWSCliente.ExecuteResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ExecuteRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ImpWSCliente.Execute", [Namespace]:="LIBRA", Order:=0)>  _
        Public Body As IMPWSCliente.ExecuteRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As IMPWSCliente.ExecuteRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="LIBRA")>  _
    Partial Public Class ExecuteRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Empid As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Emppassword As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Codigo As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Nombre As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public Razonsocial As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public Rut As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Public Documento As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=7)>  _
        Public Codigopais As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=8)>  _
        Public Codigodepartamento As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=9)>  _
        Public Localidad As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=10)>  _
        Public Direccion As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=11)>  _
        Public Codigopostal As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=12)>  _
        Public Codigozona As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=13)>  _
        Public Telefonos As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=14)>  _
        Public Celular As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=15)>  _
        Public Fax As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=16)>  _
        Public Email1 As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=17)>  _
        Public Email2 As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=18)>  _
        Public Web As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=19)>  _
        Public Codigogrupo As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=20)>  _
        Public Codigogiro As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=21)>  _
        Public Codigoorigen As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=22)>  _
        Public Codigopropietario As Short
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=23)>  _
        Public Activo As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=24)>  _
        Public Codigolocal As Short
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=25)>  _
        Public Codigocategoria As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=26)>  _
        Public Codigocondicionpago As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=27)>  _
        Public Codigoprecio As Short
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=28)>  _
        Public Descuento1 As Double
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=29)>  _
        Public Descuento2 As Double
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=30)>  _
        Public Descuento3 As Double
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=31)>  _
        Public Codigovendedor As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=32)>  _
        Public Codigomonedatope As SByte
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=33)>  _
        Public Topemontocredito As Double
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=34)>  _
        Public Topediascredito As Short
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=35)>  _
        Public Codigocuenta As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=36)>  _
        Public Codigotexto As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=37)>  _
        Public Esexento As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New( _
                    ByVal Empid As String,  _
                    ByVal Emppassword As String,  _
                    ByVal Codigo As String,  _
                    ByVal Nombre As String,  _
                    ByVal Razonsocial As String,  _
                    ByVal Rut As String,  _
                    ByVal Documento As String,  _
                    ByVal Codigopais As String,  _
                    ByVal Codigodepartamento As String,  _
                    ByVal Localidad As String,  _
                    ByVal Direccion As String,  _
                    ByVal Codigopostal As String,  _
                    ByVal Codigozona As String,  _
                    ByVal Telefonos As String,  _
                    ByVal Celular As String,  _
                    ByVal Fax As String,  _
                    ByVal Email1 As String,  _
                    ByVal Email2 As String,  _
                    ByVal Web As String,  _
                    ByVal Codigogrupo As String,  _
                    ByVal Codigogiro As String,  _
                    ByVal Codigoorigen As String,  _
                    ByVal Codigopropietario As Short,  _
                    ByVal Activo As String,  _
                    ByVal Codigolocal As Short,  _
                    ByVal Codigocategoria As String,  _
                    ByVal Codigocondicionpago As String,  _
                    ByVal Codigoprecio As Short,  _
                    ByVal Descuento1 As Double,  _
                    ByVal Descuento2 As Double,  _
                    ByVal Descuento3 As Double,  _
                    ByVal Codigovendedor As String,  _
                    ByVal Codigomonedatope As SByte,  _
                    ByVal Topemontocredito As Double,  _
                    ByVal Topediascredito As Short,  _
                    ByVal Codigocuenta As String,  _
                    ByVal Codigotexto As String,  _
                    ByVal Esexento As String)
            MyBase.New
            Me.Empid = Empid
            Me.Emppassword = Emppassword
            Me.Codigo = Codigo
            Me.Nombre = Nombre
            Me.Razonsocial = Razonsocial
            Me.Rut = Rut
            Me.Documento = Documento
            Me.Codigopais = Codigopais
            Me.Codigodepartamento = Codigodepartamento
            Me.Localidad = Localidad
            Me.Direccion = Direccion
            Me.Codigopostal = Codigopostal
            Me.Codigozona = Codigozona
            Me.Telefonos = Telefonos
            Me.Celular = Celular
            Me.Fax = Fax
            Me.Email1 = Email1
            Me.Email2 = Email2
            Me.Web = Web
            Me.Codigogrupo = Codigogrupo
            Me.Codigogiro = Codigogiro
            Me.Codigoorigen = Codigoorigen
            Me.Codigopropietario = Codigopropietario
            Me.Activo = Activo
            Me.Codigolocal = Codigolocal
            Me.Codigocategoria = Codigocategoria
            Me.Codigocondicionpago = Codigocondicionpago
            Me.Codigoprecio = Codigoprecio
            Me.Descuento1 = Descuento1
            Me.Descuento2 = Descuento2
            Me.Descuento3 = Descuento3
            Me.Codigovendedor = Codigovendedor
            Me.Codigomonedatope = Codigomonedatope
            Me.Topemontocredito = Topemontocredito
            Me.Topediascredito = Topediascredito
            Me.Codigocuenta = Codigocuenta
            Me.Codigotexto = Codigotexto
            Me.Esexento = Esexento
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ExecuteResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ImpWSCliente.ExecuteResponse", [Namespace]:="LIBRA", Order:=0)>  _
        Public Body As IMPWSCliente.ExecuteResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As IMPWSCliente.ExecuteResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="LIBRA")>  _
    Partial Public Class ExecuteResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public Ok As SByte
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public [Error] As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Ok As SByte, ByVal [Error] As String)
            MyBase.New
            Me.Ok = Ok
            Me.[Error] = [Error]
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ImpWSClienteSoapPortChannel
        Inherits IMPWSCliente.ImpWSClienteSoapPort, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ImpWSClienteSoapPortClient
        Inherits System.ServiceModel.ClientBase(Of IMPWSCliente.ImpWSClienteSoapPort)
        Implements IMPWSCliente.ImpWSClienteSoapPort
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function IMPWSCliente_ImpWSClienteSoapPort_Execute(ByVal request As IMPWSCliente.ExecuteRequest) As IMPWSCliente.ExecuteResponse Implements IMPWSCliente.ImpWSClienteSoapPort.Execute
            Return MyBase.Channel.Execute(request)
        End Function
        
        Public Function Execute( _
                    ByVal Empid As String,  _
                    ByVal Emppassword As String,  _
                    ByVal Codigo As String,  _
                    ByVal Nombre As String,  _
                    ByVal Razonsocial As String,  _
                    ByVal Rut As String,  _
                    ByVal Documento As String,  _
                    ByVal Codigopais As String,  _
                    ByVal Codigodepartamento As String,  _
                    ByVal Localidad As String,  _
                    ByVal Direccion As String,  _
                    ByVal Codigopostal As String,  _
                    ByVal Codigozona As String,  _
                    ByVal Telefonos As String,  _
                    ByVal Celular As String,  _
                    ByVal Fax As String,  _
                    ByVal Email1 As String,  _
                    ByVal Email2 As String,  _
                    ByVal Web As String,  _
                    ByVal Codigogrupo As String,  _
                    ByVal Codigogiro As String,  _
                    ByVal Codigoorigen As String,  _
                    ByVal Codigopropietario As Short,  _
                    ByVal Activo As String,  _
                    ByVal Codigolocal As Short,  _
                    ByVal Codigocategoria As String,  _
                    ByVal Codigocondicionpago As String,  _
                    ByVal Codigoprecio As Short,  _
                    ByVal Descuento1 As Double,  _
                    ByVal Descuento2 As Double,  _
                    ByVal Descuento3 As Double,  _
                    ByVal Codigovendedor As String,  _
                    ByVal Codigomonedatope As SByte,  _
                    ByVal Topemontocredito As Double,  _
                    ByVal Topediascredito As Short,  _
                    ByVal Codigocuenta As String,  _
                    ByVal Codigotexto As String,  _
                    ByVal Esexento As String,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef [Error] As String) As SByte
            Dim inValue As IMPWSCliente.ExecuteRequest = New IMPWSCliente.ExecuteRequest()
            inValue.Body = New IMPWSCliente.ExecuteRequestBody()
            inValue.Body.Empid = Empid
            inValue.Body.Emppassword = Emppassword
            inValue.Body.Codigo = Codigo
            inValue.Body.Nombre = Nombre
            inValue.Body.Razonsocial = Razonsocial
            inValue.Body.Rut = Rut
            inValue.Body.Documento = Documento
            inValue.Body.Codigopais = Codigopais
            inValue.Body.Codigodepartamento = Codigodepartamento
            inValue.Body.Localidad = Localidad
            inValue.Body.Direccion = Direccion
            inValue.Body.Codigopostal = Codigopostal
            inValue.Body.Codigozona = Codigozona
            inValue.Body.Telefonos = Telefonos
            inValue.Body.Celular = Celular
            inValue.Body.Fax = Fax
            inValue.Body.Email1 = Email1
            inValue.Body.Email2 = Email2
            inValue.Body.Web = Web
            inValue.Body.Codigogrupo = Codigogrupo
            inValue.Body.Codigogiro = Codigogiro
            inValue.Body.Codigoorigen = Codigoorigen
            inValue.Body.Codigopropietario = Codigopropietario
            inValue.Body.Activo = Activo
            inValue.Body.Codigolocal = Codigolocal
            inValue.Body.Codigocategoria = Codigocategoria
            inValue.Body.Codigocondicionpago = Codigocondicionpago
            inValue.Body.Codigoprecio = Codigoprecio
            inValue.Body.Descuento1 = Descuento1
            inValue.Body.Descuento2 = Descuento2
            inValue.Body.Descuento3 = Descuento3
            inValue.Body.Codigovendedor = Codigovendedor
            inValue.Body.Codigomonedatope = Codigomonedatope
            inValue.Body.Topemontocredito = Topemontocredito
            inValue.Body.Topediascredito = Topediascredito
            inValue.Body.Codigocuenta = Codigocuenta
            inValue.Body.Codigotexto = Codigotexto
            inValue.Body.Esexento = Esexento
            Dim retVal As IMPWSCliente.ExecuteResponse = CType(Me,IMPWSCliente.ImpWSClienteSoapPort).Execute(inValue)
            [Error] = retVal.Body.[Error]
            Return retVal.Body.Ok
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function IMPWSCliente_ImpWSClienteSoapPort_ExecuteAsync(ByVal request As IMPWSCliente.ExecuteRequest) As System.Threading.Tasks.Task(Of IMPWSCliente.ExecuteResponse) Implements IMPWSCliente.ImpWSClienteSoapPort.ExecuteAsync
            Return MyBase.Channel.ExecuteAsync(request)
        End Function
        
        Public Function ExecuteAsync( _
                    ByVal Empid As String,  _
                    ByVal Emppassword As String,  _
                    ByVal Codigo As String,  _
                    ByVal Nombre As String,  _
                    ByVal Razonsocial As String,  _
                    ByVal Rut As String,  _
                    ByVal Documento As String,  _
                    ByVal Codigopais As String,  _
                    ByVal Codigodepartamento As String,  _
                    ByVal Localidad As String,  _
                    ByVal Direccion As String,  _
                    ByVal Codigopostal As String,  _
                    ByVal Codigozona As String,  _
                    ByVal Telefonos As String,  _
                    ByVal Celular As String,  _
                    ByVal Fax As String,  _
                    ByVal Email1 As String,  _
                    ByVal Email2 As String,  _
                    ByVal Web As String,  _
                    ByVal Codigogrupo As String,  _
                    ByVal Codigogiro As String,  _
                    ByVal Codigoorigen As String,  _
                    ByVal Codigopropietario As Short,  _
                    ByVal Activo As String,  _
                    ByVal Codigolocal As Short,  _
                    ByVal Codigocategoria As String,  _
                    ByVal Codigocondicionpago As String,  _
                    ByVal Codigoprecio As Short,  _
                    ByVal Descuento1 As Double,  _
                    ByVal Descuento2 As Double,  _
                    ByVal Descuento3 As Double,  _
                    ByVal Codigovendedor As String,  _
                    ByVal Codigomonedatope As SByte,  _
                    ByVal Topemontocredito As Double,  _
                    ByVal Topediascredito As Short,  _
                    ByVal Codigocuenta As String,  _
                    ByVal Codigotexto As String,  _
                    ByVal Esexento As String) As System.Threading.Tasks.Task(Of IMPWSCliente.ExecuteResponse)
            Dim inValue As IMPWSCliente.ExecuteRequest = New IMPWSCliente.ExecuteRequest()
            inValue.Body = New IMPWSCliente.ExecuteRequestBody()
            inValue.Body.Empid = Empid
            inValue.Body.Emppassword = Emppassword
            inValue.Body.Codigo = Codigo
            inValue.Body.Nombre = Nombre
            inValue.Body.Razonsocial = Razonsocial
            inValue.Body.Rut = Rut
            inValue.Body.Documento = Documento
            inValue.Body.Codigopais = Codigopais
            inValue.Body.Codigodepartamento = Codigodepartamento
            inValue.Body.Localidad = Localidad
            inValue.Body.Direccion = Direccion
            inValue.Body.Codigopostal = Codigopostal
            inValue.Body.Codigozona = Codigozona
            inValue.Body.Telefonos = Telefonos
            inValue.Body.Celular = Celular
            inValue.Body.Fax = Fax
            inValue.Body.Email1 = Email1
            inValue.Body.Email2 = Email2
            inValue.Body.Web = Web
            inValue.Body.Codigogrupo = Codigogrupo
            inValue.Body.Codigogiro = Codigogiro
            inValue.Body.Codigoorigen = Codigoorigen
            inValue.Body.Codigopropietario = Codigopropietario
            inValue.Body.Activo = Activo
            inValue.Body.Codigolocal = Codigolocal
            inValue.Body.Codigocategoria = Codigocategoria
            inValue.Body.Codigocondicionpago = Codigocondicionpago
            inValue.Body.Codigoprecio = Codigoprecio
            inValue.Body.Descuento1 = Descuento1
            inValue.Body.Descuento2 = Descuento2
            inValue.Body.Descuento3 = Descuento3
            inValue.Body.Codigovendedor = Codigovendedor
            inValue.Body.Codigomonedatope = Codigomonedatope
            inValue.Body.Topemontocredito = Topemontocredito
            inValue.Body.Topediascredito = Topediascredito
            inValue.Body.Codigocuenta = Codigocuenta
            inValue.Body.Codigotexto = Codigotexto
            inValue.Body.Esexento = Esexento
            Return CType(Me,IMPWSCliente.ImpWSClienteSoapPort).ExecuteAsync(inValue)
        End Function
    End Class
End Namespace
