'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.17626
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace EXPWSPrecios
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="LIBRA", ConfigurationName:="EXPWSPrecios.ExpWSPreciosSoapPort")>  _
    Public Interface ExpWSPreciosSoapPort
        
        <System.ServiceModel.OperationContractAttribute(Action:="LIBRAaction/AEXPWSPRECIOS.Execute", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function Execute(ByVal request As EXPWSPrecios.ExecuteRequest) As EXPWSPrecios.ExecuteResponse
        
        'CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        <System.ServiceModel.OperationContractAttribute(Action:="LIBRAaction/AEXPWSPRECIOS.Execute", ReplyAction:="*")>  _
        Function ExecuteAsync(ByVal request As EXPWSPrecios.ExecuteRequest) As System.Threading.Tasks.Task(Of EXPWSPrecios.ExecuteResponse)
    End Interface
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17626"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(TypeName:="PreciosSDT.PrecioItem", [Namespace]:="LIBRA")>  _
    Partial Public Class PreciosSDTPrecioItem
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private codigoArticuloField As String
        
        Private codigoMonedaField As SByte
        
        Private codigoPrecioField As String
        
        Private precioSinIVAField As Double
        
        Private precioConIVAField As Double
        
        '''<comentarios/>
        Public Property CodigoArticulo() As String
            Get
                Return Me.codigoArticuloField
            End Get
            Set
                Me.codigoArticuloField = value
                Me.RaisePropertyChanged("CodigoArticulo")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CodigoMoneda() As SByte
            Get
                Return Me.codigoMonedaField
            End Get
            Set
                Me.codigoMonedaField = value
                Me.RaisePropertyChanged("CodigoMoneda")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CodigoPrecio() As String
            Get
                Return Me.codigoPrecioField
            End Get
            Set
                Me.codigoPrecioField = value
                Me.RaisePropertyChanged("CodigoPrecio")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property PrecioSinIVA() As Double
            Get
                Return Me.precioSinIVAField
            End Get
            Set
                Me.precioSinIVAField = value
                Me.RaisePropertyChanged("PrecioSinIVA")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property PrecioConIVA() As Double
            Get
                Return Me.precioConIVAField
            End Get
            Set
                Me.precioConIVAField = value
                Me.RaisePropertyChanged("PrecioConIVA")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ExpWSPrecios.Execute", WrapperNamespace:="LIBRA", IsWrapped:=true)>  _
    Partial Public Class ExecuteRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="LIBRA", Order:=0)>  _
        Public Empid As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="LIBRA", Order:=1)>  _
        Public Emppassword As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="LIBRA", Order:=2)>  _
        Public Codigo As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="LIBRA", Order:=3)>  _
        Public Codigoarticulo As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Empid As String, ByVal Emppassword As String, ByVal Codigo As String, ByVal Codigoarticulo As String)
            MyBase.New
            Me.Empid = Empid
            Me.Emppassword = Emppassword
            Me.Codigo = Codigo
            Me.Codigoarticulo = Codigoarticulo
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ExpWSPrecios.ExecuteResponse", WrapperNamespace:="LIBRA", IsWrapped:=true)>  _
    Partial Public Class ExecuteResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="LIBRA", Order:=0)>  _
        Public Ok As SByte
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="LIBRA", Order:=1)>  _
        Public [Error] As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="LIBRA", Order:=2),  _
         System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Precios() As EXPWSPrecios.PreciosSDTPrecioItem
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Ok As SByte, ByVal [Error] As String, ByVal Precios() As EXPWSPrecios.PreciosSDTPrecioItem)
            MyBase.New
            Me.Ok = Ok
            Me.[Error] = [Error]
            Me.Precios = Precios
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ExpWSPreciosSoapPortChannel
        Inherits EXPWSPrecios.ExpWSPreciosSoapPort, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ExpWSPreciosSoapPortClient
        Inherits System.ServiceModel.ClientBase(Of EXPWSPrecios.ExpWSPreciosSoapPort)
        Implements EXPWSPrecios.ExpWSPreciosSoapPort
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function EXPWSPrecios_ExpWSPreciosSoapPort_Execute(ByVal request As EXPWSPrecios.ExecuteRequest) As EXPWSPrecios.ExecuteResponse Implements EXPWSPrecios.ExpWSPreciosSoapPort.Execute
            Return MyBase.Channel.Execute(request)
        End Function
        
        Public Function Execute(ByVal Empid As String, ByVal Emppassword As String, ByVal Codigo As String, ByVal Codigoarticulo As String, <System.Runtime.InteropServices.OutAttribute()> ByRef [Error] As String, <System.Runtime.InteropServices.OutAttribute()> ByRef Precios() As EXPWSPrecios.PreciosSDTPrecioItem) As SByte
            Dim inValue As EXPWSPrecios.ExecuteRequest = New EXPWSPrecios.ExecuteRequest()
            inValue.Empid = Empid
            inValue.Emppassword = Emppassword
            inValue.Codigo = Codigo
            inValue.Codigoarticulo = Codigoarticulo
            Dim retVal As EXPWSPrecios.ExecuteResponse = CType(Me,EXPWSPrecios.ExpWSPreciosSoapPort).Execute(inValue)
            [Error] = retVal.[Error]
            Precios = retVal.Precios
            Return retVal.Ok
        End Function
        
        Public Function ExecuteAsync(ByVal request As EXPWSPrecios.ExecuteRequest) As System.Threading.Tasks.Task(Of EXPWSPrecios.ExecuteResponse) Implements EXPWSPrecios.ExpWSPreciosSoapPort.ExecuteAsync
            Return MyBase.Channel.ExecuteAsync(request)
        End Function
    End Class
End Namespace
