'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.17626
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace IMPWSPrecio
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="LIBRA", ConfigurationName:="IMPWSPrecio.ImpWSPrecioSoapPort")>  _
    Public Interface ImpWSPrecioSoapPort
        
        <System.ServiceModel.OperationContractAttribute(Action:="LIBRAaction/AIMPWSPRECIO.Execute", ReplyAction:="*")>  _
        Function Execute(ByVal request As IMPWSPrecio.ExecuteRequest) As IMPWSPrecio.ExecuteResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="LIBRAaction/AIMPWSPRECIO.Execute", ReplyAction:="*")>  _
        Function ExecuteAsync(ByVal request As IMPWSPrecio.ExecuteRequest) As System.Threading.Tasks.Task(Of IMPWSPrecio.ExecuteResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ExecuteRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ImpWSPrecio.Execute", [Namespace]:="LIBRA", Order:=0)>  _
        Public Body As IMPWSPrecio.ExecuteRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As IMPWSPrecio.ExecuteRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="LIBRA")>  _
    Partial Public Class ExecuteRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Empid As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Emppassword As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Codigoarticulo As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Codigoprecio As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=4)>  _
        Public Codigomoneda As SByte
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=5)>  _
        Public Preciosiniva As Double
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=6)>  _
        Public Precioconiva As Double
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Empid As String, ByVal Emppassword As String, ByVal Codigoarticulo As String, ByVal Codigoprecio As String, ByVal Codigomoneda As SByte, ByVal Preciosiniva As Double, ByVal Precioconiva As Double)
            MyBase.New
            Me.Empid = Empid
            Me.Emppassword = Emppassword
            Me.Codigoarticulo = Codigoarticulo
            Me.Codigoprecio = Codigoprecio
            Me.Codigomoneda = Codigomoneda
            Me.Preciosiniva = Preciosiniva
            Me.Precioconiva = Precioconiva
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ExecuteResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ImpWSPrecio.ExecuteResponse", [Namespace]:="LIBRA", Order:=0)>  _
        Public Body As IMPWSPrecio.ExecuteResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As IMPWSPrecio.ExecuteResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="LIBRA")>  _
    Partial Public Class ExecuteResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public Ok As SByte
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public [Error] As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Ok As SByte, ByVal [Error] As String)
            MyBase.New
            Me.Ok = Ok
            Me.[Error] = [Error]
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ImpWSPrecioSoapPortChannel
        Inherits IMPWSPrecio.ImpWSPrecioSoapPort, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ImpWSPrecioSoapPortClient
        Inherits System.ServiceModel.ClientBase(Of IMPWSPrecio.ImpWSPrecioSoapPort)
        Implements IMPWSPrecio.ImpWSPrecioSoapPort
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function IMPWSPrecio_ImpWSPrecioSoapPort_Execute(ByVal request As IMPWSPrecio.ExecuteRequest) As IMPWSPrecio.ExecuteResponse Implements IMPWSPrecio.ImpWSPrecioSoapPort.Execute
            Return MyBase.Channel.Execute(request)
        End Function
        
        Public Function Execute(ByVal Empid As String, ByVal Emppassword As String, ByVal Codigoarticulo As String, ByVal Codigoprecio As String, ByVal Codigomoneda As SByte, ByVal Preciosiniva As Double, ByVal Precioconiva As Double, <System.Runtime.InteropServices.OutAttribute()> ByRef [Error] As String) As SByte
            Dim inValue As IMPWSPrecio.ExecuteRequest = New IMPWSPrecio.ExecuteRequest()
            inValue.Body = New IMPWSPrecio.ExecuteRequestBody()
            inValue.Body.Empid = Empid
            inValue.Body.Emppassword = Emppassword
            inValue.Body.Codigoarticulo = Codigoarticulo
            inValue.Body.Codigoprecio = Codigoprecio
            inValue.Body.Codigomoneda = Codigomoneda
            inValue.Body.Preciosiniva = Preciosiniva
            inValue.Body.Precioconiva = Precioconiva
            Dim retVal As IMPWSPrecio.ExecuteResponse = CType(Me,IMPWSPrecio.ImpWSPrecioSoapPort).Execute(inValue)
            [Error] = retVal.Body.[Error]
            Return retVal.Body.Ok
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function IMPWSPrecio_ImpWSPrecioSoapPort_ExecuteAsync(ByVal request As IMPWSPrecio.ExecuteRequest) As System.Threading.Tasks.Task(Of IMPWSPrecio.ExecuteResponse) Implements IMPWSPrecio.ImpWSPrecioSoapPort.ExecuteAsync
            Return MyBase.Channel.ExecuteAsync(request)
        End Function
        
        Public Function ExecuteAsync(ByVal Empid As String, ByVal Emppassword As String, ByVal Codigoarticulo As String, ByVal Codigoprecio As String, ByVal Codigomoneda As SByte, ByVal Preciosiniva As Double, ByVal Precioconiva As Double) As System.Threading.Tasks.Task(Of IMPWSPrecio.ExecuteResponse)
            Dim inValue As IMPWSPrecio.ExecuteRequest = New IMPWSPrecio.ExecuteRequest()
            inValue.Body = New IMPWSPrecio.ExecuteRequestBody()
            inValue.Body.Empid = Empid
            inValue.Body.Emppassword = Emppassword
            inValue.Body.Codigoarticulo = Codigoarticulo
            inValue.Body.Codigoprecio = Codigoprecio
            inValue.Body.Codigomoneda = Codigomoneda
            inValue.Body.Preciosiniva = Preciosiniva
            inValue.Body.Precioconiva = Precioconiva
            Return CType(Me,IMPWSPrecio.ImpWSPrecioSoapPort).ExecuteAsync(inValue)
        End Function
    End Class
End Namespace
