'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.17626
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace IMPWSArticulo
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="LIBRA", ConfigurationName:="IMPWSArticulo.ImpWSArticuloSoapPort")>  _
    Public Interface ImpWSArticuloSoapPort
        
        <System.ServiceModel.OperationContractAttribute(Action:="LIBRAaction/AIMPWSARTICULO.Execute", ReplyAction:="*")>  _
        Function Execute(ByVal request As IMPWSArticulo.ExecuteRequest) As IMPWSArticulo.ExecuteResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="LIBRAaction/AIMPWSARTICULO.Execute", ReplyAction:="*")>  _
        Function ExecuteAsync(ByVal request As IMPWSArticulo.ExecuteRequest) As System.Threading.Tasks.Task(Of IMPWSArticulo.ExecuteResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ExecuteRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ImpWSArticulo.Execute", [Namespace]:="LIBRA", Order:=0)>  _
        Public Body As IMPWSArticulo.ExecuteRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As IMPWSArticulo.ExecuteRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="LIBRA")>  _
    Partial Public Class ExecuteRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Empid As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Emppassword As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Codigo As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Nombre As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public Abreviacion As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public Codigocategoria As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Public Codigofamilia As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=7)>  _
        Public Codigomarca As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=8)>  _
        Public Codigoproveedor As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=9)>  _
        Public Codigoiva As SByte
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=10)>  _
        Public Cuentacompras As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=11)>  _
        Public Cuentaventas As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=12)>  _
        Public Cuentaproduccion As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=13)>  _
        Public Codigoorigen As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=14)>  _
        Public Codigounidad As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=15)>  _
        Public Web As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=16)>  _
        Public Codigotexto As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=17)>  _
        Public Notas As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=18)>  _
        Public Activo As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=19)>  _
        Public Listadeprecios As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=20)>  _
        Public Usastock As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=21)>  _
        Public Usalotes As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=22)>  _
        Public Usavencimientos As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=23)>  _
        Public Codigomonedacostos As SByte
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=24)>  _
        Public Fechacosto As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=25)>  _
        Public Costo As Double
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=26)>  _
        Public Porcentajeutilidad As Double
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New( _
                    ByVal Empid As String,  _
                    ByVal Emppassword As String,  _
                    ByVal Codigo As String,  _
                    ByVal Nombre As String,  _
                    ByVal Abreviacion As String,  _
                    ByVal Codigocategoria As String,  _
                    ByVal Codigofamilia As String,  _
                    ByVal Codigomarca As String,  _
                    ByVal Codigoproveedor As String,  _
                    ByVal Codigoiva As SByte,  _
                    ByVal Cuentacompras As String,  _
                    ByVal Cuentaventas As String,  _
                    ByVal Cuentaproduccion As String,  _
                    ByVal Codigoorigen As String,  _
                    ByVal Codigounidad As String,  _
                    ByVal Web As String,  _
                    ByVal Codigotexto As String,  _
                    ByVal Notas As String,  _
                    ByVal Activo As String,  _
                    ByVal Listadeprecios As String,  _
                    ByVal Usastock As String,  _
                    ByVal Usalotes As String,  _
                    ByVal Usavencimientos As String,  _
                    ByVal Codigomonedacostos As SByte,  _
                    ByVal Fechacosto As String,  _
                    ByVal Costo As Double,  _
                    ByVal Porcentajeutilidad As Double)
            MyBase.New
            Me.Empid = Empid
            Me.Emppassword = Emppassword
            Me.Codigo = Codigo
            Me.Nombre = Nombre
            Me.Abreviacion = Abreviacion
            Me.Codigocategoria = Codigocategoria
            Me.Codigofamilia = Codigofamilia
            Me.Codigomarca = Codigomarca
            Me.Codigoproveedor = Codigoproveedor
            Me.Codigoiva = Codigoiva
            Me.Cuentacompras = Cuentacompras
            Me.Cuentaventas = Cuentaventas
            Me.Cuentaproduccion = Cuentaproduccion
            Me.Codigoorigen = Codigoorigen
            Me.Codigounidad = Codigounidad
            Me.Web = Web
            Me.Codigotexto = Codigotexto
            Me.Notas = Notas
            Me.Activo = Activo
            Me.Listadeprecios = Listadeprecios
            Me.Usastock = Usastock
            Me.Usalotes = Usalotes
            Me.Usavencimientos = Usavencimientos
            Me.Codigomonedacostos = Codigomonedacostos
            Me.Fechacosto = Fechacosto
            Me.Costo = Costo
            Me.Porcentajeutilidad = Porcentajeutilidad
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ExecuteResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ImpWSArticulo.ExecuteResponse", [Namespace]:="LIBRA", Order:=0)>  _
        Public Body As IMPWSArticulo.ExecuteResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As IMPWSArticulo.ExecuteResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="LIBRA")>  _
    Partial Public Class ExecuteResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public Ok As SByte
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public [Error] As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Ok As SByte, ByVal [Error] As String)
            MyBase.New
            Me.Ok = Ok
            Me.[Error] = [Error]
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ImpWSArticuloSoapPortChannel
        Inherits IMPWSArticulo.ImpWSArticuloSoapPort, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ImpWSArticuloSoapPortClient
        Inherits System.ServiceModel.ClientBase(Of IMPWSArticulo.ImpWSArticuloSoapPort)
        Implements IMPWSArticulo.ImpWSArticuloSoapPort
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function IMPWSArticulo_ImpWSArticuloSoapPort_Execute(ByVal request As IMPWSArticulo.ExecuteRequest) As IMPWSArticulo.ExecuteResponse Implements IMPWSArticulo.ImpWSArticuloSoapPort.Execute
            Return MyBase.Channel.Execute(request)
        End Function
        
        Public Function Execute( _
                    ByVal Empid As String,  _
                    ByVal Emppassword As String,  _
                    ByVal Codigo As String,  _
                    ByVal Nombre As String,  _
                    ByVal Abreviacion As String,  _
                    ByVal Codigocategoria As String,  _
                    ByVal Codigofamilia As String,  _
                    ByVal Codigomarca As String,  _
                    ByVal Codigoproveedor As String,  _
                    ByVal Codigoiva As SByte,  _
                    ByVal Cuentacompras As String,  _
                    ByVal Cuentaventas As String,  _
                    ByVal Cuentaproduccion As String,  _
                    ByVal Codigoorigen As String,  _
                    ByVal Codigounidad As String,  _
                    ByVal Web As String,  _
                    ByVal Codigotexto As String,  _
                    ByVal Notas As String,  _
                    ByVal Activo As String,  _
                    ByVal Listadeprecios As String,  _
                    ByVal Usastock As String,  _
                    ByVal Usalotes As String,  _
                    ByVal Usavencimientos As String,  _
                    ByVal Codigomonedacostos As SByte,  _
                    ByVal Fechacosto As String,  _
                    ByVal Costo As Double,  _
                    ByVal Porcentajeutilidad As Double,  _
                    <System.Runtime.InteropServices.OutAttribute()> ByRef [Error] As String) As SByte
            Dim inValue As IMPWSArticulo.ExecuteRequest = New IMPWSArticulo.ExecuteRequest()
            inValue.Body = New IMPWSArticulo.ExecuteRequestBody()
            inValue.Body.Empid = Empid
            inValue.Body.Emppassword = Emppassword
            inValue.Body.Codigo = Codigo
            inValue.Body.Nombre = Nombre
            inValue.Body.Abreviacion = Abreviacion
            inValue.Body.Codigocategoria = Codigocategoria
            inValue.Body.Codigofamilia = Codigofamilia
            inValue.Body.Codigomarca = Codigomarca
            inValue.Body.Codigoproveedor = Codigoproveedor
            inValue.Body.Codigoiva = Codigoiva
            inValue.Body.Cuentacompras = Cuentacompras
            inValue.Body.Cuentaventas = Cuentaventas
            inValue.Body.Cuentaproduccion = Cuentaproduccion
            inValue.Body.Codigoorigen = Codigoorigen
            inValue.Body.Codigounidad = Codigounidad
            inValue.Body.Web = Web
            inValue.Body.Codigotexto = Codigotexto
            inValue.Body.Notas = Notas
            inValue.Body.Activo = Activo
            inValue.Body.Listadeprecios = Listadeprecios
            inValue.Body.Usastock = Usastock
            inValue.Body.Usalotes = Usalotes
            inValue.Body.Usavencimientos = Usavencimientos
            inValue.Body.Codigomonedacostos = Codigomonedacostos
            inValue.Body.Fechacosto = Fechacosto
            inValue.Body.Costo = Costo
            inValue.Body.Porcentajeutilidad = Porcentajeutilidad
            Dim retVal As IMPWSArticulo.ExecuteResponse = CType(Me,IMPWSArticulo.ImpWSArticuloSoapPort).Execute(inValue)
            [Error] = retVal.Body.[Error]
            Return retVal.Body.Ok
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function IMPWSArticulo_ImpWSArticuloSoapPort_ExecuteAsync(ByVal request As IMPWSArticulo.ExecuteRequest) As System.Threading.Tasks.Task(Of IMPWSArticulo.ExecuteResponse) Implements IMPWSArticulo.ImpWSArticuloSoapPort.ExecuteAsync
            Return MyBase.Channel.ExecuteAsync(request)
        End Function
        
        Public Function ExecuteAsync( _
                    ByVal Empid As String,  _
                    ByVal Emppassword As String,  _
                    ByVal Codigo As String,  _
                    ByVal Nombre As String,  _
                    ByVal Abreviacion As String,  _
                    ByVal Codigocategoria As String,  _
                    ByVal Codigofamilia As String,  _
                    ByVal Codigomarca As String,  _
                    ByVal Codigoproveedor As String,  _
                    ByVal Codigoiva As SByte,  _
                    ByVal Cuentacompras As String,  _
                    ByVal Cuentaventas As String,  _
                    ByVal Cuentaproduccion As String,  _
                    ByVal Codigoorigen As String,  _
                    ByVal Codigounidad As String,  _
                    ByVal Web As String,  _
                    ByVal Codigotexto As String,  _
                    ByVal Notas As String,  _
                    ByVal Activo As String,  _
                    ByVal Listadeprecios As String,  _
                    ByVal Usastock As String,  _
                    ByVal Usalotes As String,  _
                    ByVal Usavencimientos As String,  _
                    ByVal Codigomonedacostos As SByte,  _
                    ByVal Fechacosto As String,  _
                    ByVal Costo As Double,  _
                    ByVal Porcentajeutilidad As Double) As System.Threading.Tasks.Task(Of IMPWSArticulo.ExecuteResponse)
            Dim inValue As IMPWSArticulo.ExecuteRequest = New IMPWSArticulo.ExecuteRequest()
            inValue.Body = New IMPWSArticulo.ExecuteRequestBody()
            inValue.Body.Empid = Empid
            inValue.Body.Emppassword = Emppassword
            inValue.Body.Codigo = Codigo
            inValue.Body.Nombre = Nombre
            inValue.Body.Abreviacion = Abreviacion
            inValue.Body.Codigocategoria = Codigocategoria
            inValue.Body.Codigofamilia = Codigofamilia
            inValue.Body.Codigomarca = Codigomarca
            inValue.Body.Codigoproveedor = Codigoproveedor
            inValue.Body.Codigoiva = Codigoiva
            inValue.Body.Cuentacompras = Cuentacompras
            inValue.Body.Cuentaventas = Cuentaventas
            inValue.Body.Cuentaproduccion = Cuentaproduccion
            inValue.Body.Codigoorigen = Codigoorigen
            inValue.Body.Codigounidad = Codigounidad
            inValue.Body.Web = Web
            inValue.Body.Codigotexto = Codigotexto
            inValue.Body.Notas = Notas
            inValue.Body.Activo = Activo
            inValue.Body.Listadeprecios = Listadeprecios
            inValue.Body.Usastock = Usastock
            inValue.Body.Usalotes = Usalotes
            inValue.Body.Usavencimientos = Usavencimientos
            inValue.Body.Codigomonedacostos = Codigomonedacostos
            inValue.Body.Fechacosto = Fechacosto
            inValue.Body.Costo = Costo
            inValue.Body.Porcentajeutilidad = Porcentajeutilidad
            Return CType(Me,IMPWSArticulo.ImpWSArticuloSoapPort).ExecuteAsync(inValue)
        End Function
    End Class
End Namespace
