//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegrationZetaPrueba2.EXPWSMovements {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="LIBRA", ConfigurationName="EXPWSMovements.ExpWSMovimientosSoapPort")]
    public interface ExpWSMovimientosSoapPort {
        
        [System.ServiceModel.OperationContractAttribute(Action="LIBRAaction/AEXPWSMOVIMIENTOS.Execute", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        global::IntegrationZetaPrueba2.EXPWSMovements.ExecuteResponse Execute(global::IntegrationZetaPrueba2.EXPWSMovements.ExecuteRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="LIBRAaction/AEXPWSMOVIMIENTOS.Execute", ReplyAction="*")]
        System.Threading.Tasks.Task<global::IntegrationZetaPrueba2.EXPWSMovements.ExecuteResponse> ExecuteAsync(global::IntegrationZetaPrueba2.EXPWSMovements.ExecuteRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="ExpMovimientosSDT.MovimientoItem", Namespace="LIBRA")]
    public partial class ExpMovimientosSDTMovimientoItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private short codigoComprobanteField;
        
        private string serieField;
        
        private long numeroField;
        
        private string fechaField;
        
        private sbyte codigoMonedaField;
        
        private double cotizacionField;
        
        private string codigoClienteField;
        
        private string codigoVendedorField;
        
        private short codigoPrecioField;
        
        private string codigoCondicionPagoField;
        
        private short codigoDepositoOrigenField;
        
        private short codigoDepositoDestinoField;
        
        private string fechaEntregaField;
        
        private string codigoCentroCostoField;
        
        private string codigoReferenciaField;
        
        private string notasField;
        
        private double totalReciboField;
        
        private short codigoLocalField;
        
        private short codigoUsuarioField;
        
        private short codigoCajaField;
        
        private ExpMovimientosSDTMovimientoItemLineaItem[] lineasField;
        
        private ExpMovimientosSDTMovimientoItemFormaPagoItem[] formasPagoField;
        
        /// <remarks/>
        public short CodigoComprobante {
            get {
                return this.codigoComprobanteField;
            }
            set {
                this.codigoComprobanteField = value;
                this.RaisePropertyChanged("CodigoComprobante");
            }
        }
        
        /// <remarks/>
        public string Serie {
            get {
                return this.serieField;
            }
            set {
                this.serieField = value;
                this.RaisePropertyChanged("Serie");
            }
        }
        
        /// <remarks/>
        public long Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
                this.RaisePropertyChanged("Numero");
            }
        }
        
        /// <remarks/>
        public string Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("Fecha");
            }
        }
        
        /// <remarks/>
        public sbyte CodigoMoneda {
            get {
                return this.codigoMonedaField;
            }
            set {
                this.codigoMonedaField = value;
                this.RaisePropertyChanged("CodigoMoneda");
            }
        }
        
        /// <remarks/>
        public double Cotizacion {
            get {
                return this.cotizacionField;
            }
            set {
                this.cotizacionField = value;
                this.RaisePropertyChanged("Cotizacion");
            }
        }
        
        /// <remarks/>
        public string CodigoCliente {
            get {
                return this.codigoClienteField;
            }
            set {
                this.codigoClienteField = value;
                this.RaisePropertyChanged("CodigoCliente");
            }
        }
        
        /// <remarks/>
        public string CodigoVendedor {
            get {
                return this.codigoVendedorField;
            }
            set {
                this.codigoVendedorField = value;
                this.RaisePropertyChanged("CodigoVendedor");
            }
        }
        
        /// <remarks/>
        public short CodigoPrecio {
            get {
                return this.codigoPrecioField;
            }
            set {
                this.codigoPrecioField = value;
                this.RaisePropertyChanged("CodigoPrecio");
            }
        }
        
        /// <remarks/>
        public string CodigoCondicionPago {
            get {
                return this.codigoCondicionPagoField;
            }
            set {
                this.codigoCondicionPagoField = value;
                this.RaisePropertyChanged("CodigoCondicionPago");
            }
        }
        
        /// <remarks/>
        public short CodigoDepositoOrigen {
            get {
                return this.codigoDepositoOrigenField;
            }
            set {
                this.codigoDepositoOrigenField = value;
                this.RaisePropertyChanged("CodigoDepositoOrigen");
            }
        }
        
        /// <remarks/>
        public short CodigoDepositoDestino {
            get {
                return this.codigoDepositoDestinoField;
            }
            set {
                this.codigoDepositoDestinoField = value;
                this.RaisePropertyChanged("CodigoDepositoDestino");
            }
        }
        
        /// <remarks/>
        public string FechaEntrega {
            get {
                return this.fechaEntregaField;
            }
            set {
                this.fechaEntregaField = value;
                this.RaisePropertyChanged("FechaEntrega");
            }
        }
        
        /// <remarks/>
        public string CodigoCentroCosto {
            get {
                return this.codigoCentroCostoField;
            }
            set {
                this.codigoCentroCostoField = value;
                this.RaisePropertyChanged("CodigoCentroCosto");
            }
        }
        
        /// <remarks/>
        public string CodigoReferencia {
            get {
                return this.codigoReferenciaField;
            }
            set {
                this.codigoReferenciaField = value;
                this.RaisePropertyChanged("CodigoReferencia");
            }
        }
        
        /// <remarks/>
        public string Notas {
            get {
                return this.notasField;
            }
            set {
                this.notasField = value;
                this.RaisePropertyChanged("Notas");
            }
        }
        
        /// <remarks/>
        public double TotalRecibo {
            get {
                return this.totalReciboField;
            }
            set {
                this.totalReciboField = value;
                this.RaisePropertyChanged("TotalRecibo");
            }
        }
        
        /// <remarks/>
        public short CodigoLocal {
            get {
                return this.codigoLocalField;
            }
            set {
                this.codigoLocalField = value;
                this.RaisePropertyChanged("CodigoLocal");
            }
        }
        
        /// <remarks/>
        public short CodigoUsuario {
            get {
                return this.codigoUsuarioField;
            }
            set {
                this.codigoUsuarioField = value;
                this.RaisePropertyChanged("CodigoUsuario");
            }
        }
        
        /// <remarks/>
        public short CodigoCaja {
            get {
                return this.codigoCajaField;
            }
            set {
                this.codigoCajaField = value;
                this.RaisePropertyChanged("CodigoCaja");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ExpMovimientosSDTMovimientoItemLineaItem[] Lineas {
            get {
                return this.lineasField;
            }
            set {
                this.lineasField = value;
                this.RaisePropertyChanged("Lineas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ExpMovimientosSDTMovimientoItemFormaPagoItem[] FormasPago {
            get {
                return this.formasPagoField;
            }
            set {
                this.formasPagoField = value;
                this.RaisePropertyChanged("FormasPago");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="ExpMovimientosSDT.MovimientoItem.LineaItem", Namespace="LIBRA")]
    public partial class ExpMovimientosSDTMovimientoItemLineaItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoArticuloField;
        
        private string conceptoField;
        
        private string codigoLoteField;
        
        private string vencimientoField;
        
        private double cantidadField;
        
        private double precioUnitarioField;
        
        private double descuento1Field;
        
        private double descuento2Field;
        
        private double descuento3Field;
        
        private double netoField;
        
        private double iVAField;
        
        private double totalField;
        
        private string notasField;
        
        /// <remarks/>
        public string CodigoArticulo {
            get {
                return this.codigoArticuloField;
            }
            set {
                this.codigoArticuloField = value;
                this.RaisePropertyChanged("CodigoArticulo");
            }
        }
        
        /// <remarks/>
        public string Concepto {
            get {
                return this.conceptoField;
            }
            set {
                this.conceptoField = value;
                this.RaisePropertyChanged("Concepto");
            }
        }
        
        /// <remarks/>
        public string CodigoLote {
            get {
                return this.codigoLoteField;
            }
            set {
                this.codigoLoteField = value;
                this.RaisePropertyChanged("CodigoLote");
            }
        }
        
        /// <remarks/>
        public string Vencimiento {
            get {
                return this.vencimientoField;
            }
            set {
                this.vencimientoField = value;
                this.RaisePropertyChanged("Vencimiento");
            }
        }
        
        /// <remarks/>
        public double Cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("Cantidad");
            }
        }
        
        /// <remarks/>
        public double PrecioUnitario {
            get {
                return this.precioUnitarioField;
            }
            set {
                this.precioUnitarioField = value;
                this.RaisePropertyChanged("PrecioUnitario");
            }
        }
        
        /// <remarks/>
        public double Descuento1 {
            get {
                return this.descuento1Field;
            }
            set {
                this.descuento1Field = value;
                this.RaisePropertyChanged("Descuento1");
            }
        }
        
        /// <remarks/>
        public double Descuento2 {
            get {
                return this.descuento2Field;
            }
            set {
                this.descuento2Field = value;
                this.RaisePropertyChanged("Descuento2");
            }
        }
        
        /// <remarks/>
        public double Descuento3 {
            get {
                return this.descuento3Field;
            }
            set {
                this.descuento3Field = value;
                this.RaisePropertyChanged("Descuento3");
            }
        }
        
        /// <remarks/>
        public double Neto {
            get {
                return this.netoField;
            }
            set {
                this.netoField = value;
                this.RaisePropertyChanged("Neto");
            }
        }
        
        /// <remarks/>
        public double IVA {
            get {
                return this.iVAField;
            }
            set {
                this.iVAField = value;
                this.RaisePropertyChanged("IVA");
            }
        }
        
        /// <remarks/>
        public double Total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("Total");
            }
        }
        
        /// <remarks/>
        public string Notas {
            get {
                return this.notasField;
            }
            set {
                this.notasField = value;
                this.RaisePropertyChanged("Notas");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="ExpMovimientosSDT.MovimientoItem.FormaPagoItem.Documento", Namespace="LIBRA")]
    public partial class ExpMovimientosSDTMovimientoItemFormaPagoItemDocumento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private short codigoComprobanteField;
        
        private string serieField;
        
        private long numeroField;
        
        private string fechaEmisionField;
        
        private string fechaVencimientoField;
        
        private string conceptoField;
        
        private short codigoCajaField;
        
        private string codigoBancoFinancieraField;
        
        private string titularField;
        
        private string numeroTarjetaField;
        
        private string autorizacionTarjetaField;
        
        private string planTarjetaField;
        
        private short codigoCtaBancariaField;
        
        /// <remarks/>
        public short CodigoComprobante {
            get {
                return this.codigoComprobanteField;
            }
            set {
                this.codigoComprobanteField = value;
                this.RaisePropertyChanged("CodigoComprobante");
            }
        }
        
        /// <remarks/>
        public string Serie {
            get {
                return this.serieField;
            }
            set {
                this.serieField = value;
                this.RaisePropertyChanged("Serie");
            }
        }
        
        /// <remarks/>
        public long Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
                this.RaisePropertyChanged("Numero");
            }
        }
        
        /// <remarks/>
        public string FechaEmision {
            get {
                return this.fechaEmisionField;
            }
            set {
                this.fechaEmisionField = value;
                this.RaisePropertyChanged("FechaEmision");
            }
        }
        
        /// <remarks/>
        public string FechaVencimiento {
            get {
                return this.fechaVencimientoField;
            }
            set {
                this.fechaVencimientoField = value;
                this.RaisePropertyChanged("FechaVencimiento");
            }
        }
        
        /// <remarks/>
        public string Concepto {
            get {
                return this.conceptoField;
            }
            set {
                this.conceptoField = value;
                this.RaisePropertyChanged("Concepto");
            }
        }
        
        /// <remarks/>
        public short CodigoCaja {
            get {
                return this.codigoCajaField;
            }
            set {
                this.codigoCajaField = value;
                this.RaisePropertyChanged("CodigoCaja");
            }
        }
        
        /// <remarks/>
        public string CodigoBancoFinanciera {
            get {
                return this.codigoBancoFinancieraField;
            }
            set {
                this.codigoBancoFinancieraField = value;
                this.RaisePropertyChanged("CodigoBancoFinanciera");
            }
        }
        
        /// <remarks/>
        public string Titular {
            get {
                return this.titularField;
            }
            set {
                this.titularField = value;
                this.RaisePropertyChanged("Titular");
            }
        }
        
        /// <remarks/>
        public string NumeroTarjeta {
            get {
                return this.numeroTarjetaField;
            }
            set {
                this.numeroTarjetaField = value;
                this.RaisePropertyChanged("NumeroTarjeta");
            }
        }
        
        /// <remarks/>
        public string AutorizacionTarjeta {
            get {
                return this.autorizacionTarjetaField;
            }
            set {
                this.autorizacionTarjetaField = value;
                this.RaisePropertyChanged("AutorizacionTarjeta");
            }
        }
        
        /// <remarks/>
        public string PlanTarjeta {
            get {
                return this.planTarjetaField;
            }
            set {
                this.planTarjetaField = value;
                this.RaisePropertyChanged("PlanTarjeta");
            }
        }
        
        /// <remarks/>
        public short CodigoCtaBancaria {
            get {
                return this.codigoCtaBancariaField;
            }
            set {
                this.codigoCtaBancariaField = value;
                this.RaisePropertyChanged("CodigoCtaBancaria");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="ExpMovimientosSDT.MovimientoItem.FormaPagoItem", Namespace="LIBRA")]
    public partial class ExpMovimientosSDTMovimientoItemFormaPagoItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private sbyte codigoFormaPagoField;
        
        private sbyte codigoMonedaPagoField;
        
        private double montoMonedaPagoField;
        
        private double montoMonedaMovimientoField;
        
        private ExpMovimientosSDTMovimientoItemFormaPagoItemDocumento documentoField;
        
        /// <remarks/>
        public sbyte CodigoFormaPago {
            get {
                return this.codigoFormaPagoField;
            }
            set {
                this.codigoFormaPagoField = value;
                this.RaisePropertyChanged("CodigoFormaPago");
            }
        }
        
        /// <remarks/>
        public sbyte CodigoMonedaPago {
            get {
                return this.codigoMonedaPagoField;
            }
            set {
                this.codigoMonedaPagoField = value;
                this.RaisePropertyChanged("CodigoMonedaPago");
            }
        }
        
        /// <remarks/>
        public double MontoMonedaPago {
            get {
                return this.montoMonedaPagoField;
            }
            set {
                this.montoMonedaPagoField = value;
                this.RaisePropertyChanged("MontoMonedaPago");
            }
        }
        
        /// <remarks/>
        public double MontoMonedaMovimiento {
            get {
                return this.montoMonedaMovimientoField;
            }
            set {
                this.montoMonedaMovimientoField = value;
                this.RaisePropertyChanged("MontoMonedaMovimiento");
            }
        }
        
        /// <remarks/>
        public ExpMovimientosSDTMovimientoItemFormaPagoItemDocumento Documento {
            get {
                return this.documentoField;
            }
            set {
                this.documentoField = value;
                this.RaisePropertyChanged("Documento");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExpWSMovimientos.Execute", WrapperNamespace="LIBRA", IsWrapped=true)]
    public partial class ExecuteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="LIBRA", Order=0)]
        public string Empid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="LIBRA", Order=1)]
        public string Emppassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="LIBRA", Order=2)]
        public short Codigocomprobante;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="LIBRA", Order=3)]
        public string Serie;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="LIBRA", Order=4)]
        public long Numero;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="LIBRA", Order=5)]
        public string Fechaini;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="LIBRA", Order=6)]
        public string Fechafin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="LIBRA", Order=7)]
        public string Codigocliente;
        
        public ExecuteRequest() {
        }
        
        public ExecuteRequest(string Empid, string Emppassword, short Codigocomprobante, string Serie, long Numero, string Fechaini, string Fechafin, string Codigocliente) {
            this.Empid = Empid;
            this.Emppassword = Emppassword;
            this.Codigocomprobante = Codigocomprobante;
            this.Serie = Serie;
            this.Numero = Numero;
            this.Fechaini = Fechaini;
            this.Fechafin = Fechafin;
            this.Codigocliente = Codigocliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExpWSMovimientos.ExecuteResponse", WrapperNamespace="LIBRA", IsWrapped=true)]
    public partial class ExecuteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="LIBRA", Order=0)]
        public sbyte Ok;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="LIBRA", Order=1)]
        public string Error;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="LIBRA", Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public IntegrationZetaPrueba2.EXPWSMovements.ExpMovimientosSDTMovimientoItem[] Movimientos;
        
        public ExecuteResponse() {
        }
        
        public ExecuteResponse(sbyte Ok, string Error, IntegrationZetaPrueba2.EXPWSMovements.ExpMovimientosSDTMovimientoItem[] Movimientos) {
            this.Ok = Ok;
            this.Error = Error;
            this.Movimientos = Movimientos;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ExpWSMovimientosSoapPortChannel : global::IntegrationZetaPrueba2.EXPWSMovements.ExpWSMovimientosSoapPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExpWSMovimientosSoapPortClient : System.ServiceModel.ClientBase<global::IntegrationZetaPrueba2.EXPWSMovements.ExpWSMovimientosSoapPort>, global::IntegrationZetaPrueba2.EXPWSMovements.ExpWSMovimientosSoapPort {
        
        public ExpWSMovimientosSoapPortClient() {
        }
        
        public ExpWSMovimientosSoapPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExpWSMovimientosSoapPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExpWSMovimientosSoapPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExpWSMovimientosSoapPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        global::IntegrationZetaPrueba2.EXPWSMovements.ExecuteResponse global::IntegrationZetaPrueba2.EXPWSMovements.ExpWSMovimientosSoapPort.Execute(global::IntegrationZetaPrueba2.EXPWSMovements.ExecuteRequest request) {
            return base.Channel.Execute(request);
        }
        
        public sbyte Execute(string Empid, string Emppassword, short Codigocomprobante, string Serie, long Numero, string Fechaini, string Fechafin, string Codigocliente, out string Error, out IntegrationZetaPrueba2.EXPWSMovements.ExpMovimientosSDTMovimientoItem[] Movimientos) {
            global::IntegrationZetaPrueba2.EXPWSMovements.ExecuteRequest inValue = new global::IntegrationZetaPrueba2.EXPWSMovements.ExecuteRequest();
            inValue.Empid = Empid;
            inValue.Emppassword = Emppassword;
            inValue.Codigocomprobante = Codigocomprobante;
            inValue.Serie = Serie;
            inValue.Numero = Numero;
            inValue.Fechaini = Fechaini;
            inValue.Fechafin = Fechafin;
            inValue.Codigocliente = Codigocliente;
            global::IntegrationZetaPrueba2.EXPWSMovements.ExecuteResponse retVal = ((global::IntegrationZetaPrueba2.EXPWSMovements.ExpWSMovimientosSoapPort)(this)).Execute(inValue);
            Error = retVal.Error;
            Movimientos = retVal.Movimientos;
            return retVal.Ok;
        }
        
        public System.Threading.Tasks.Task<global::IntegrationZetaPrueba2.EXPWSMovements.ExecuteResponse> ExecuteAsync(global::IntegrationZetaPrueba2.EXPWSMovements.ExecuteRequest request) {
            return base.Channel.ExecuteAsync(request);
        }
    }
}
