'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.17929
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace EXPWSComprobantesPendientes
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="LIBRA", ConfigurationName:="EXPWSComprobantesPendientes.ExpWSComprobantesPendientesSoapPort")>  _
    Public Interface ExpWSComprobantesPendientesSoapPort
        
        <System.ServiceModel.OperationContractAttribute(Action:="LIBRAaction/AEXPWSCOMPROBANTESPENDIENTES.Execute", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Execute(ByVal request As EXPWSComprobantesPendientes.ExecuteRequest) As EXPWSComprobantesPendientes.ExecuteResponse
        
        'CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        <System.ServiceModel.OperationContractAttribute(Action:="LIBRAaction/AEXPWSCOMPROBANTESPENDIENTES.Execute", ReplyAction:="*")>  _
        Function ExecuteAsync(ByVal request As EXPWSComprobantesPendientes.ExecuteRequest) As System.Threading.Tasks.Task(Of EXPWSComprobantesPendientes.ExecuteResponse)
    End Interface
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(TypeName:="CmpPendientesSdt.CmpPendientesItem", [Namespace]:="LIBRA")>  _
    Partial Public Class CmpPendientesSdtCmpPendientesItem
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private codigoComprobanteField As Short
        
        Private serieField As String
        
        Private numeroField As Long
        
        Private codigoClienteField As String
        
        Private fechaField As String
        
        Private codigoMonedaField As SByte
        
        Private totalField As Double
        
        Private pendienteField As Double
        
        '''<comentarios/>
        Public Property CodigoComprobante() As Short
            Get
                Return Me.codigoComprobanteField
            End Get
            Set
                Me.codigoComprobanteField = value
                Me.RaisePropertyChanged("CodigoComprobante")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Serie() As String
            Get
                Return Me.serieField
            End Get
            Set
                Me.serieField = value
                Me.RaisePropertyChanged("Serie")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Numero() As Long
            Get
                Return Me.numeroField
            End Get
            Set
                Me.numeroField = value
                Me.RaisePropertyChanged("Numero")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CodigoCliente() As String
            Get
                Return Me.codigoClienteField
            End Get
            Set
                Me.codigoClienteField = value
                Me.RaisePropertyChanged("CodigoCliente")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Fecha() As String
            Get
                Return Me.fechaField
            End Get
            Set
                Me.fechaField = value
                Me.RaisePropertyChanged("Fecha")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CodigoMoneda() As SByte
            Get
                Return Me.codigoMonedaField
            End Get
            Set
                Me.codigoMonedaField = value
                Me.RaisePropertyChanged("CodigoMoneda")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Total() As Double
            Get
                Return Me.totalField
            End Get
            Set
                Me.totalField = value
                Me.RaisePropertyChanged("Total")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Pendiente() As Double
            Get
                Return Me.pendienteField
            End Get
            Set
                Me.pendienteField = value
                Me.RaisePropertyChanged("Pendiente")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ExpWSComprobantesPendientes.Execute", WrapperNamespace:="LIBRA", IsWrapped:=true)>  _
    Partial Public Class ExecuteRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="LIBRA", Order:=0)>  _
        Public Empid As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="LIBRA", Order:=1)>  _
        Public Emppassword As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="LIBRA", Order:=2)>  _
        Public Codigocliente As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Empid As String, ByVal Emppassword As String, ByVal Codigocliente As String)
            MyBase.New
            Me.Empid = Empid
            Me.Emppassword = Emppassword
            Me.Codigocliente = Codigocliente
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ExpWSComprobantesPendientes.ExecuteResponse", WrapperNamespace:="LIBRA", IsWrapped:=true)>  _
    Partial Public Class ExecuteResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="LIBRA", Order:=0)>  _
        Public Ok As SByte
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="LIBRA", Order:=1)>  _
        Public [Error] As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="LIBRA", Order:=2),  _
         System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Comprobantespendientes() As EXPWSComprobantesPendientes.CmpPendientesSdtCmpPendientesItem
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Ok As SByte, ByVal [Error] As String, ByVal Comprobantespendientes() As EXPWSComprobantesPendientes.CmpPendientesSdtCmpPendientesItem)
            MyBase.New
            Me.Ok = Ok
            Me.[Error] = [Error]
            Me.Comprobantespendientes = Comprobantespendientes
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ExpWSComprobantesPendientesSoapPortChannel
        Inherits EXPWSComprobantesPendientes.ExpWSComprobantesPendientesSoapPort, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ExpWSComprobantesPendientesSoapPortClient
        Inherits System.ServiceModel.ClientBase(Of EXPWSComprobantesPendientes.ExpWSComprobantesPendientesSoapPort)
        Implements EXPWSComprobantesPendientes.ExpWSComprobantesPendientesSoapPort
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function EXPWSComprobantesPendientes_ExpWSComprobantesPendientesSoapPort_Execute(ByVal request As EXPWSComprobantesPendientes.ExecuteRequest) As EXPWSComprobantesPendientes.ExecuteResponse Implements EXPWSComprobantesPendientes.ExpWSComprobantesPendientesSoapPort.Execute
            Return MyBase.Channel.Execute(request)
        End Function
        
        Public Function Execute(ByVal Empid As String, ByVal Emppassword As String, ByVal Codigocliente As String, <System.Runtime.InteropServices.OutAttribute()> ByRef [Error] As String, <System.Runtime.InteropServices.OutAttribute()> ByRef Comprobantespendientes() As EXPWSComprobantesPendientes.CmpPendientesSdtCmpPendientesItem) As SByte
            Dim inValue As EXPWSComprobantesPendientes.ExecuteRequest = New EXPWSComprobantesPendientes.ExecuteRequest()
            inValue.Empid = Empid
            inValue.Emppassword = Emppassword
            inValue.Codigocliente = Codigocliente
            Dim retVal As EXPWSComprobantesPendientes.ExecuteResponse = CType(Me,EXPWSComprobantesPendientes.ExpWSComprobantesPendientesSoapPort).Execute(inValue)
            [Error] = retVal.[Error]
            Comprobantespendientes = retVal.Comprobantespendientes
            Return retVal.Ok
        End Function
        
        Public Function ExecuteAsync(ByVal request As EXPWSComprobantesPendientes.ExecuteRequest) As System.Threading.Tasks.Task(Of EXPWSComprobantesPendientes.ExecuteResponse) Implements EXPWSComprobantesPendientes.ExpWSComprobantesPendientesSoapPort.ExecuteAsync
            Return MyBase.Channel.ExecuteAsync(request)
        End Function
    End Class
End Namespace
