//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegrationZetaPrueba2.EXPWSStock {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="LIBRA", ConfigurationName="EXPWSStock.ExpWSStockActualSoapPort")]
    public interface ExpWSStockActualSoapPort {
        
        [System.ServiceModel.OperationContractAttribute(Action="LIBRAaction/AEXPWSSTOCKACTUAL.Execute", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        global::IntegrationZetaPrueba2.EXPWSStock.ExecuteResponse Execute(global::IntegrationZetaPrueba2.EXPWSStock.ExecuteRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="LIBRAaction/AEXPWSSTOCKACTUAL.Execute", ReplyAction="*")]
        System.Threading.Tasks.Task<global::IntegrationZetaPrueba2.EXPWSStock.ExecuteResponse> ExecuteAsync(global::IntegrationZetaPrueba2.EXPWSStock.ExecuteRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="StockActualSdt.StockActualItem", Namespace="LIBRA")]
    public partial class StockActualSdtStockActualItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private short codigoDepositoField;
        
        private string codigoArticuloField;
        
        private string codigoLoteField;
        
        private string vencimientoLoteField;
        
        private double stockField;
        
        /// <remarks/>
        public short CodigoDeposito {
            get {
                return this.codigoDepositoField;
            }
            set {
                this.codigoDepositoField = value;
                this.RaisePropertyChanged("CodigoDeposito");
            }
        }
        
        /// <remarks/>
        public string CodigoArticulo {
            get {
                return this.codigoArticuloField;
            }
            set {
                this.codigoArticuloField = value;
                this.RaisePropertyChanged("CodigoArticulo");
            }
        }
        
        /// <remarks/>
        public string CodigoLote {
            get {
                return this.codigoLoteField;
            }
            set {
                this.codigoLoteField = value;
                this.RaisePropertyChanged("CodigoLote");
            }
        }
        
        /// <remarks/>
        public string VencimientoLote {
            get {
                return this.vencimientoLoteField;
            }
            set {
                this.vencimientoLoteField = value;
                this.RaisePropertyChanged("VencimientoLote");
            }
        }
        
        /// <remarks/>
        public double Stock {
            get {
                return this.stockField;
            }
            set {
                this.stockField = value;
                this.RaisePropertyChanged("Stock");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExpWSStockActual.Execute", WrapperNamespace="LIBRA", IsWrapped=true)]
    public partial class ExecuteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="LIBRA", Order=0)]
        public string Empid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="LIBRA", Order=1)]
        public string Emppassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="LIBRA", Order=2)]
        public string Codigoarticulo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="LIBRA", Order=3)]
        public short Codigodeposito;
        
        public ExecuteRequest() {
        }
        
        public ExecuteRequest(string Empid, string Emppassword, string Codigoarticulo, short Codigodeposito) {
            this.Empid = Empid;
            this.Emppassword = Emppassword;
            this.Codigoarticulo = Codigoarticulo;
            this.Codigodeposito = Codigodeposito;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExpWSStockActual.ExecuteResponse", WrapperNamespace="LIBRA", IsWrapped=true)]
    public partial class ExecuteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="LIBRA", Order=0)]
        public sbyte Ok;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="LIBRA", Order=1)]
        public string Error;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="LIBRA", Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public IntegrationZetaPrueba2.EXPWSStock.StockActualSdtStockActualItem[] Stockactualsdt;
        
        public ExecuteResponse() {
        }
        
        public ExecuteResponse(sbyte Ok, string Error, IntegrationZetaPrueba2.EXPWSStock.StockActualSdtStockActualItem[] Stockactualsdt) {
            this.Ok = Ok;
            this.Error = Error;
            this.Stockactualsdt = Stockactualsdt;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ExpWSStockActualSoapPortChannel : global::IntegrationZetaPrueba2.EXPWSStock.ExpWSStockActualSoapPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExpWSStockActualSoapPortClient : System.ServiceModel.ClientBase<global::IntegrationZetaPrueba2.EXPWSStock.ExpWSStockActualSoapPort>, global::IntegrationZetaPrueba2.EXPWSStock.ExpWSStockActualSoapPort {
        
        public ExpWSStockActualSoapPortClient() {
        }
        
        public ExpWSStockActualSoapPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExpWSStockActualSoapPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExpWSStockActualSoapPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExpWSStockActualSoapPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        global::IntegrationZetaPrueba2.EXPWSStock.ExecuteResponse global::IntegrationZetaPrueba2.EXPWSStock.ExpWSStockActualSoapPort.Execute(global::IntegrationZetaPrueba2.EXPWSStock.ExecuteRequest request) {
            return base.Channel.Execute(request);
        }
        
        public sbyte Execute(string Empid, string Emppassword, string Codigoarticulo, short Codigodeposito, out string Error, out IntegrationZetaPrueba2.EXPWSStock.StockActualSdtStockActualItem[] Stockactualsdt) {
            global::IntegrationZetaPrueba2.EXPWSStock.ExecuteRequest inValue = new global::IntegrationZetaPrueba2.EXPWSStock.ExecuteRequest();
            inValue.Empid = Empid;
            inValue.Emppassword = Emppassword;
            inValue.Codigoarticulo = Codigoarticulo;
            inValue.Codigodeposito = Codigodeposito;
            global::IntegrationZetaPrueba2.EXPWSStock.ExecuteResponse retVal = ((global::IntegrationZetaPrueba2.EXPWSStock.ExpWSStockActualSoapPort)(this)).Execute(inValue);
            Error = retVal.Error;
            Stockactualsdt = retVal.Stockactualsdt;
            return retVal.Ok;
        }
        
        public System.Threading.Tasks.Task<global::IntegrationZetaPrueba2.EXPWSStock.ExecuteResponse> ExecuteAsync(global::IntegrationZetaPrueba2.EXPWSStock.ExecuteRequest request) {
            return base.Channel.ExecuteAsync(request);
        }
    }
}
