'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18063
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace EXPWSArticulos2
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="LIBRA", ConfigurationName:="EXPWSArticulos2.ExpWSArticulosSoapPort")>  _
    Public Interface ExpWSArticulosSoapPort
        
        <System.ServiceModel.OperationContractAttribute(Action:="LIBRAaction/AEXPWSARTICULOS.Execute", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function Execute(ByVal request As EXPWSArticulos2.ExecuteRequest) As EXPWSArticulos2.ExecuteResponse
        
        'CODEGEN: Generating message contract since the operation has multiple return values.
        <System.ServiceModel.OperationContractAttribute(Action:="LIBRAaction/AEXPWSARTICULOS.Execute", ReplyAction:="*")>  _
        Function ExecuteAsync(ByVal request As EXPWSArticulos2.ExecuteRequest) As System.Threading.Tasks.Task(Of EXPWSArticulos2.ExecuteResponse)
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(TypeName:="ArticulosSDT.ArticuloItem", [Namespace]:="LIBRA")>  _
    Partial Public Class ArticulosSDTArticuloItem
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private codigoField As String
        
        Private nombreField As String
        
        Private abreviacionField As String
        
        Private codigoCategoriaField As String
        
        Private codigoFamiliaField As String
        
        Private codigoMarcaField As String
        
        Private codigoProveedorField As String
        
        Private codigoIVAField As SByte
        
        Private cuentaComprasField As String
        
        Private cuentaVentasField As String
        
        Private cuentaProduccionField As String
        
        Private codigoOrigenField As String
        
        Private codigoUnidadField As String
        
        Private webField As String
        
        Private codigoTextoField As String
        
        Private notasField As String
        
        Private activoField As String
        
        Private listaDePreciosField As String
        
        Private usaStockField As String
        
        Private usaLotesField As String
        
        Private usaVencimientosField As String
        
        Private codigoMonedaCostosField As SByte
        
        Private fechaCostoField As String
        
        Private costoField As Double
        
        Private porcentajeUtilidadField As Double
        
        '''<remarks/>
        Public Property Codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
                Me.RaisePropertyChanged("Codigo")
            End Set
        End Property
        
        '''<remarks/>
        Public Property Nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
                Me.RaisePropertyChanged("Nombre")
            End Set
        End Property
        
        '''<remarks/>
        Public Property Abreviacion() As String
            Get
                Return Me.abreviacionField
            End Get
            Set
                Me.abreviacionField = value
                Me.RaisePropertyChanged("Abreviacion")
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodigoCategoria() As String
            Get
                Return Me.codigoCategoriaField
            End Get
            Set
                Me.codigoCategoriaField = value
                Me.RaisePropertyChanged("CodigoCategoria")
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodigoFamilia() As String
            Get
                Return Me.codigoFamiliaField
            End Get
            Set
                Me.codigoFamiliaField = value
                Me.RaisePropertyChanged("CodigoFamilia")
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodigoMarca() As String
            Get
                Return Me.codigoMarcaField
            End Get
            Set
                Me.codigoMarcaField = value
                Me.RaisePropertyChanged("CodigoMarca")
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodigoProveedor() As String
            Get
                Return Me.codigoProveedorField
            End Get
            Set
                Me.codigoProveedorField = value
                Me.RaisePropertyChanged("CodigoProveedor")
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodigoIVA() As SByte
            Get
                Return Me.codigoIVAField
            End Get
            Set
                Me.codigoIVAField = value
                Me.RaisePropertyChanged("CodigoIVA")
            End Set
        End Property
        
        '''<remarks/>
        Public Property CuentaCompras() As String
            Get
                Return Me.cuentaComprasField
            End Get
            Set
                Me.cuentaComprasField = value
                Me.RaisePropertyChanged("CuentaCompras")
            End Set
        End Property
        
        '''<remarks/>
        Public Property CuentaVentas() As String
            Get
                Return Me.cuentaVentasField
            End Get
            Set
                Me.cuentaVentasField = value
                Me.RaisePropertyChanged("CuentaVentas")
            End Set
        End Property
        
        '''<remarks/>
        Public Property CuentaProduccion() As String
            Get
                Return Me.cuentaProduccionField
            End Get
            Set
                Me.cuentaProduccionField = value
                Me.RaisePropertyChanged("CuentaProduccion")
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodigoOrigen() As String
            Get
                Return Me.codigoOrigenField
            End Get
            Set
                Me.codigoOrigenField = value
                Me.RaisePropertyChanged("CodigoOrigen")
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodigoUnidad() As String
            Get
                Return Me.codigoUnidadField
            End Get
            Set
                Me.codigoUnidadField = value
                Me.RaisePropertyChanged("CodigoUnidad")
            End Set
        End Property
        
        '''<remarks/>
        Public Property Web() As String
            Get
                Return Me.webField
            End Get
            Set
                Me.webField = value
                Me.RaisePropertyChanged("Web")
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodigoTexto() As String
            Get
                Return Me.codigoTextoField
            End Get
            Set
                Me.codigoTextoField = value
                Me.RaisePropertyChanged("CodigoTexto")
            End Set
        End Property
        
        '''<remarks/>
        Public Property Notas() As String
            Get
                Return Me.notasField
            End Get
            Set
                Me.notasField = value
                Me.RaisePropertyChanged("Notas")
            End Set
        End Property
        
        '''<remarks/>
        Public Property Activo() As String
            Get
                Return Me.activoField
            End Get
            Set
                Me.activoField = value
                Me.RaisePropertyChanged("Activo")
            End Set
        End Property
        
        '''<remarks/>
        Public Property ListaDePrecios() As String
            Get
                Return Me.listaDePreciosField
            End Get
            Set
                Me.listaDePreciosField = value
                Me.RaisePropertyChanged("ListaDePrecios")
            End Set
        End Property
        
        '''<remarks/>
        Public Property UsaStock() As String
            Get
                Return Me.usaStockField
            End Get
            Set
                Me.usaStockField = value
                Me.RaisePropertyChanged("UsaStock")
            End Set
        End Property
        
        '''<remarks/>
        Public Property UsaLotes() As String
            Get
                Return Me.usaLotesField
            End Get
            Set
                Me.usaLotesField = value
                Me.RaisePropertyChanged("UsaLotes")
            End Set
        End Property
        
        '''<remarks/>
        Public Property UsaVencimientos() As String
            Get
                Return Me.usaVencimientosField
            End Get
            Set
                Me.usaVencimientosField = value
                Me.RaisePropertyChanged("UsaVencimientos")
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodigoMonedaCostos() As SByte
            Get
                Return Me.codigoMonedaCostosField
            End Get
            Set
                Me.codigoMonedaCostosField = value
                Me.RaisePropertyChanged("CodigoMonedaCostos")
            End Set
        End Property
        
        '''<remarks/>
        Public Property FechaCosto() As String
            Get
                Return Me.fechaCostoField
            End Get
            Set
                Me.fechaCostoField = value
                Me.RaisePropertyChanged("FechaCosto")
            End Set
        End Property
        
        '''<remarks/>
        Public Property Costo() As Double
            Get
                Return Me.costoField
            End Get
            Set
                Me.costoField = value
                Me.RaisePropertyChanged("Costo")
            End Set
        End Property
        
        '''<remarks/>
        Public Property PorcentajeUtilidad() As Double
            Get
                Return Me.porcentajeUtilidadField
            End Get
            Set
                Me.porcentajeUtilidadField = value
                Me.RaisePropertyChanged("PorcentajeUtilidad")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ExpWSArticulos.Execute", WrapperNamespace:="LIBRA", IsWrapped:=true)>  _
    Partial Public Class ExecuteRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="LIBRA", Order:=0)>  _
        Public Empid As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="LIBRA", Order:=1)>  _
        Public Emppassword As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="LIBRA", Order:=2)>  _
        Public Codigo As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="LIBRA", Order:=3)>  _
        Public Fechaini As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="LIBRA", Order:=4)>  _
        Public Fechafin As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Empid As String, ByVal Emppassword As String, ByVal Codigo As String, ByVal Fechaini As String, ByVal Fechafin As String)
            MyBase.New
            Me.Empid = Empid
            Me.Emppassword = Emppassword
            Me.Codigo = Codigo
            Me.Fechaini = Fechaini
            Me.Fechafin = Fechafin
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ExpWSArticulos.ExecuteResponse", WrapperNamespace:="LIBRA", IsWrapped:=true)>  _
    Partial Public Class ExecuteResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="LIBRA", Order:=0)>  _
        Public Ok As SByte
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="LIBRA", Order:=1)>  _
        Public [Error] As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="LIBRA", Order:=2),  _
         System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Articulos() As EXPWSArticulos2.ArticulosSDTArticuloItem
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Ok As SByte, ByVal [Error] As String, ByVal Articulos() As EXPWSArticulos2.ArticulosSDTArticuloItem)
            MyBase.New
            Me.Ok = Ok
            Me.[Error] = [Error]
            Me.Articulos = Articulos
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ExpWSArticulosSoapPortChannel
        Inherits EXPWSArticulos2.ExpWSArticulosSoapPort, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ExpWSArticulosSoapPortClient
        Inherits System.ServiceModel.ClientBase(Of EXPWSArticulos2.ExpWSArticulosSoapPort)
        Implements EXPWSArticulos2.ExpWSArticulosSoapPort
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function EXPWSArticulos2_ExpWSArticulosSoapPort_Execute(ByVal request As EXPWSArticulos2.ExecuteRequest) As EXPWSArticulos2.ExecuteResponse Implements EXPWSArticulos2.ExpWSArticulosSoapPort.Execute
            Return MyBase.Channel.Execute(request)
        End Function
        
        Public Function Execute(ByVal Empid As String, ByVal Emppassword As String, ByVal Codigo As String, ByVal Fechaini As String, ByVal Fechafin As String, <System.Runtime.InteropServices.OutAttribute()> ByRef [Error] As String, <System.Runtime.InteropServices.OutAttribute()> ByRef Articulos() As EXPWSArticulos2.ArticulosSDTArticuloItem) As SByte
            Dim inValue As EXPWSArticulos2.ExecuteRequest = New EXPWSArticulos2.ExecuteRequest()
            inValue.Empid = Empid
            inValue.Emppassword = Emppassword
            inValue.Codigo = Codigo
            inValue.Fechaini = Fechaini
            inValue.Fechafin = Fechafin
            Dim retVal As EXPWSArticulos2.ExecuteResponse = CType(Me,EXPWSArticulos2.ExpWSArticulosSoapPort).Execute(inValue)
            [Error] = retVal.[Error]
            Articulos = retVal.Articulos
            Return retVal.Ok
        End Function
        
        Public Function ExecuteAsync(ByVal request As EXPWSArticulos2.ExecuteRequest) As System.Threading.Tasks.Task(Of EXPWSArticulos2.ExecuteResponse) Implements EXPWSArticulos2.ExpWSArticulosSoapPort.ExecuteAsync
            Return MyBase.Channel.ExecuteAsync(request)
        End Function
    End Class
End Namespace
