'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.17929
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace IMPWSMovimiento
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="LIBRA", ConfigurationName:="IMPWSMovimiento.ImpWSMovimientoSoapPort")>  _
    Public Interface ImpWSMovimientoSoapPort
        
        <System.ServiceModel.OperationContractAttribute(Action:="LIBRAaction/AIMPWSMOVIMIENTO.Execute", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Execute(ByVal request As IMPWSMovimiento.ExecuteRequest) As IMPWSMovimiento.ExecuteResponse
        
        'CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        <System.ServiceModel.OperationContractAttribute(Action:="LIBRAaction/AIMPWSMOVIMIENTO.Execute", ReplyAction:="*")>  _
        Function ExecuteAsync(ByVal request As IMPWSMovimiento.ExecuteRequest) As System.Threading.Tasks.Task(Of IMPWSMovimiento.ExecuteResponse)
    End Interface
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(TypeName:="MovimientosSDT.MovimientoItem", [Namespace]:="LIBRA")>  _
    Partial Public Class MovimientosSDTMovimientoItem
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private codigoComprobanteField As Short
        
        Private serieField As String
        
        Private numeroField As Long
        
        Private fechaField As String
        
        Private codigoMonedaField As SByte
        
        Private cotizacionField As Double
        
        Private codigoClienteField As String
        
        Private codigoVendedorField As String
        
        Private codigoPrecioField As Short
        
        Private codigoCondicionPagoField As String
        
        Private codigoDepositoOrigenField As Short
        
        Private codigoDepositoDestinoField As Short
        
        Private fechaEntregaField As String
        
        Private codigoCentroCostoField As String
        
        Private codigoReferenciaField As String
        
        Private notasField As String
        
        Private totalReciboField As Double
        
        Private codigoLocalField As Short
        
        Private codigoUsuarioField As Short
        
        Private codigoCajaField As Short
        
        Private lineasField() As MovimientosSDTMovimientoItemLineaItem
        
        Private formasPagoField() As MovimientosSDTMovimientoItemFormaPagoItem
        
        '''<comentarios/>
        Public Property CodigoComprobante() As Short
            Get
                Return Me.codigoComprobanteField
            End Get
            Set
                Me.codigoComprobanteField = value
                Me.RaisePropertyChanged("CodigoComprobante")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Serie() As String
            Get
                Return Me.serieField
            End Get
            Set
                Me.serieField = value
                Me.RaisePropertyChanged("Serie")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Numero() As Long
            Get
                Return Me.numeroField
            End Get
            Set
                Me.numeroField = value
                Me.RaisePropertyChanged("Numero")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Fecha() As String
            Get
                Return Me.fechaField
            End Get
            Set
                Me.fechaField = value
                Me.RaisePropertyChanged("Fecha")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CodigoMoneda() As SByte
            Get
                Return Me.codigoMonedaField
            End Get
            Set
                Me.codigoMonedaField = value
                Me.RaisePropertyChanged("CodigoMoneda")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Cotizacion() As Double
            Get
                Return Me.cotizacionField
            End Get
            Set
                Me.cotizacionField = value
                Me.RaisePropertyChanged("Cotizacion")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CodigoCliente() As String
            Get
                Return Me.codigoClienteField
            End Get
            Set
                Me.codigoClienteField = value
                Me.RaisePropertyChanged("CodigoCliente")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CodigoVendedor() As String
            Get
                Return Me.codigoVendedorField
            End Get
            Set
                Me.codigoVendedorField = value
                Me.RaisePropertyChanged("CodigoVendedor")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CodigoPrecio() As Short
            Get
                Return Me.codigoPrecioField
            End Get
            Set
                Me.codigoPrecioField = value
                Me.RaisePropertyChanged("CodigoPrecio")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CodigoCondicionPago() As String
            Get
                Return Me.codigoCondicionPagoField
            End Get
            Set
                Me.codigoCondicionPagoField = value
                Me.RaisePropertyChanged("CodigoCondicionPago")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CodigoDepositoOrigen() As Short
            Get
                Return Me.codigoDepositoOrigenField
            End Get
            Set
                Me.codigoDepositoOrigenField = value
                Me.RaisePropertyChanged("CodigoDepositoOrigen")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CodigoDepositoDestino() As Short
            Get
                Return Me.codigoDepositoDestinoField
            End Get
            Set
                Me.codigoDepositoDestinoField = value
                Me.RaisePropertyChanged("CodigoDepositoDestino")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property FechaEntrega() As String
            Get
                Return Me.fechaEntregaField
            End Get
            Set
                Me.fechaEntregaField = value
                Me.RaisePropertyChanged("FechaEntrega")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CodigoCentroCosto() As String
            Get
                Return Me.codigoCentroCostoField
            End Get
            Set
                Me.codigoCentroCostoField = value
                Me.RaisePropertyChanged("CodigoCentroCosto")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CodigoReferencia() As String
            Get
                Return Me.codigoReferenciaField
            End Get
            Set
                Me.codigoReferenciaField = value
                Me.RaisePropertyChanged("CodigoReferencia")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Notas() As String
            Get
                Return Me.notasField
            End Get
            Set
                Me.notasField = value
                Me.RaisePropertyChanged("Notas")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property TotalRecibo() As Double
            Get
                Return Me.totalReciboField
            End Get
            Set
                Me.totalReciboField = value
                Me.RaisePropertyChanged("TotalRecibo")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CodigoLocal() As Short
            Get
                Return Me.codigoLocalField
            End Get
            Set
                Me.codigoLocalField = value
                Me.RaisePropertyChanged("CodigoLocal")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CodigoUsuario() As Short
            Get
                Return Me.codigoUsuarioField
            End Get
            Set
                Me.codigoUsuarioField = value
                Me.RaisePropertyChanged("CodigoUsuario")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CodigoCaja() As Short
            Get
                Return Me.codigoCajaField
            End Get
            Set
                Me.codigoCajaField = value
                Me.RaisePropertyChanged("CodigoCaja")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property Lineas() As MovimientosSDTMovimientoItemLineaItem()
            Get
                Return Me.lineasField
            End Get
            Set
                Me.lineasField = value
                Me.RaisePropertyChanged("Lineas")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property FormasPago() As MovimientosSDTMovimientoItemFormaPagoItem()
            Get
                Return Me.formasPagoField
            End Get
            Set
                Me.formasPagoField = value
                Me.RaisePropertyChanged("FormasPago")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(TypeName:="MovimientosSDT.MovimientoItem.LineaItem", [Namespace]:="LIBRA")>  _
    Partial Public Class MovimientosSDTMovimientoItemLineaItem
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private codigoArticuloField As String
        
        Private conceptoField As String
        
        Private codigoLoteField As String
        
        Private vencimientoField As String
        
        Private cantidadField As Double
        
        Private precioUnitarioField As Double
        
        Private descuento1Field As Double
        
        Private descuento2Field As Double
        
        Private descuento3Field As Double
        
        Private notasField As String
        
        '''<comentarios/>
        Public Property CodigoArticulo() As String
            Get
                Return Me.codigoArticuloField
            End Get
            Set
                Me.codigoArticuloField = value
                Me.RaisePropertyChanged("CodigoArticulo")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Concepto() As String
            Get
                Return Me.conceptoField
            End Get
            Set
                Me.conceptoField = value
                Me.RaisePropertyChanged("Concepto")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CodigoLote() As String
            Get
                Return Me.codigoLoteField
            End Get
            Set
                Me.codigoLoteField = value
                Me.RaisePropertyChanged("CodigoLote")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Vencimiento() As String
            Get
                Return Me.vencimientoField
            End Get
            Set
                Me.vencimientoField = value
                Me.RaisePropertyChanged("Vencimiento")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Cantidad() As Double
            Get
                Return Me.cantidadField
            End Get
            Set
                Me.cantidadField = value
                Me.RaisePropertyChanged("Cantidad")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property PrecioUnitario() As Double
            Get
                Return Me.precioUnitarioField
            End Get
            Set
                Me.precioUnitarioField = value
                Me.RaisePropertyChanged("PrecioUnitario")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Descuento1() As Double
            Get
                Return Me.descuento1Field
            End Get
            Set
                Me.descuento1Field = value
                Me.RaisePropertyChanged("Descuento1")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Descuento2() As Double
            Get
                Return Me.descuento2Field
            End Get
            Set
                Me.descuento2Field = value
                Me.RaisePropertyChanged("Descuento2")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Descuento3() As Double
            Get
                Return Me.descuento3Field
            End Get
            Set
                Me.descuento3Field = value
                Me.RaisePropertyChanged("Descuento3")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Notas() As String
            Get
                Return Me.notasField
            End Get
            Set
                Me.notasField = value
                Me.RaisePropertyChanged("Notas")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(TypeName:="MovimientosSDT.MovimientoItem.FormaPagoItem.Documento", [Namespace]:="LIBRA")>  _
    Partial Public Class MovimientosSDTMovimientoItemFormaPagoItemDocumento
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private codigoComprobanteField As Short
        
        Private serieField As String
        
        Private numeroField As Long
        
        Private fechaEmisionField As String
        
        Private fechaVencimientoField As String
        
        Private conceptoField As String
        
        Private codigoCajaField As Short
        
        Private codigoBancoFinancieraField As String
        
        Private titularField As String
        
        Private numeroTarjetaField As String
        
        Private autorizacionTarjetaField As String
        
        Private planTarjetaField As String
        
        Private codigoCtaBancariaField As Short
        
        '''<comentarios/>
        Public Property CodigoComprobante() As Short
            Get
                Return Me.codigoComprobanteField
            End Get
            Set
                Me.codigoComprobanteField = value
                Me.RaisePropertyChanged("CodigoComprobante")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Serie() As String
            Get
                Return Me.serieField
            End Get
            Set
                Me.serieField = value
                Me.RaisePropertyChanged("Serie")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Numero() As Long
            Get
                Return Me.numeroField
            End Get
            Set
                Me.numeroField = value
                Me.RaisePropertyChanged("Numero")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property FechaEmision() As String
            Get
                Return Me.fechaEmisionField
            End Get
            Set
                Me.fechaEmisionField = value
                Me.RaisePropertyChanged("FechaEmision")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property FechaVencimiento() As String
            Get
                Return Me.fechaVencimientoField
            End Get
            Set
                Me.fechaVencimientoField = value
                Me.RaisePropertyChanged("FechaVencimiento")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Concepto() As String
            Get
                Return Me.conceptoField
            End Get
            Set
                Me.conceptoField = value
                Me.RaisePropertyChanged("Concepto")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CodigoCaja() As Short
            Get
                Return Me.codigoCajaField
            End Get
            Set
                Me.codigoCajaField = value
                Me.RaisePropertyChanged("CodigoCaja")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CodigoBancoFinanciera() As String
            Get
                Return Me.codigoBancoFinancieraField
            End Get
            Set
                Me.codigoBancoFinancieraField = value
                Me.RaisePropertyChanged("CodigoBancoFinanciera")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Titular() As String
            Get
                Return Me.titularField
            End Get
            Set
                Me.titularField = value
                Me.RaisePropertyChanged("Titular")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property NumeroTarjeta() As String
            Get
                Return Me.numeroTarjetaField
            End Get
            Set
                Me.numeroTarjetaField = value
                Me.RaisePropertyChanged("NumeroTarjeta")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property AutorizacionTarjeta() As String
            Get
                Return Me.autorizacionTarjetaField
            End Get
            Set
                Me.autorizacionTarjetaField = value
                Me.RaisePropertyChanged("AutorizacionTarjeta")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property PlanTarjeta() As String
            Get
                Return Me.planTarjetaField
            End Get
            Set
                Me.planTarjetaField = value
                Me.RaisePropertyChanged("PlanTarjeta")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CodigoCtaBancaria() As Short
            Get
                Return Me.codigoCtaBancariaField
            End Get
            Set
                Me.codigoCtaBancariaField = value
                Me.RaisePropertyChanged("CodigoCtaBancaria")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(TypeName:="MovimientosSDT.MovimientoItem.FormaPagoItem", [Namespace]:="LIBRA")>  _
    Partial Public Class MovimientosSDTMovimientoItemFormaPagoItem
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private codigoFormaPagoField As SByte
        
        Private codigoMonedaPagoField As SByte
        
        Private montoMonedaPagoField As Double
        
        Private montoMonedaMovimientoField As Double
        
        Private documentoField As MovimientosSDTMovimientoItemFormaPagoItemDocumento
        
        '''<comentarios/>
        Public Property CodigoFormaPago() As SByte
            Get
                Return Me.codigoFormaPagoField
            End Get
            Set
                Me.codigoFormaPagoField = value
                Me.RaisePropertyChanged("CodigoFormaPago")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CodigoMonedaPago() As SByte
            Get
                Return Me.codigoMonedaPagoField
            End Get
            Set
                Me.codigoMonedaPagoField = value
                Me.RaisePropertyChanged("CodigoMonedaPago")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property MontoMonedaPago() As Double
            Get
                Return Me.montoMonedaPagoField
            End Get
            Set
                Me.montoMonedaPagoField = value
                Me.RaisePropertyChanged("MontoMonedaPago")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property MontoMonedaMovimiento() As Double
            Get
                Return Me.montoMonedaMovimientoField
            End Get
            Set
                Me.montoMonedaMovimientoField = value
                Me.RaisePropertyChanged("MontoMonedaMovimiento")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Documento() As MovimientosSDTMovimientoItemFormaPagoItemDocumento
            Get
                Return Me.documentoField
            End Get
            Set
                Me.documentoField = value
                Me.RaisePropertyChanged("Documento")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ImpWSMovimiento.Execute", WrapperNamespace:="LIBRA", IsWrapped:=true)>  _
    Partial Public Class ExecuteRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="LIBRA", Order:=0)>  _
        Public Empid As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="LIBRA", Order:=1)>  _
        Public Emppassword As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="LIBRA", Order:=2)>  _
        Public Movimiento As IMPWSMovimiento.MovimientosSDTMovimientoItem
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Empid As String, ByVal Emppassword As String, ByVal Movimiento As IMPWSMovimiento.MovimientosSDTMovimientoItem)
            MyBase.New
            Me.Empid = Empid
            Me.Emppassword = Emppassword
            Me.Movimiento = Movimiento
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ImpWSMovimiento.ExecuteResponse", WrapperNamespace:="LIBRA", IsWrapped:=true)>  _
    Partial Public Class ExecuteResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="LIBRA", Order:=0)>  _
        Public Ok As SByte
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="LIBRA", Order:=1)>  _
        Public [Error] As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Ok As SByte, ByVal [Error] As String)
            MyBase.New
            Me.Ok = Ok
            Me.[Error] = [Error]
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ImpWSMovimientoSoapPortChannel
        Inherits IMPWSMovimiento.ImpWSMovimientoSoapPort, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ImpWSMovimientoSoapPortClient
        Inherits System.ServiceModel.ClientBase(Of IMPWSMovimiento.ImpWSMovimientoSoapPort)
        Implements IMPWSMovimiento.ImpWSMovimientoSoapPort
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function IMPWSMovimiento_ImpWSMovimientoSoapPort_Execute(ByVal request As IMPWSMovimiento.ExecuteRequest) As IMPWSMovimiento.ExecuteResponse Implements IMPWSMovimiento.ImpWSMovimientoSoapPort.Execute
            Return MyBase.Channel.Execute(request)
        End Function
        
        Public Function Execute(ByVal Empid As String, ByVal Emppassword As String, ByVal Movimiento As IMPWSMovimiento.MovimientosSDTMovimientoItem, <System.Runtime.InteropServices.OutAttribute()> ByRef [Error] As String) As SByte
            Dim inValue As IMPWSMovimiento.ExecuteRequest = New IMPWSMovimiento.ExecuteRequest()
            inValue.Empid = Empid
            inValue.Emppassword = Emppassword
            inValue.Movimiento = Movimiento
            Dim retVal As IMPWSMovimiento.ExecuteResponse = CType(Me,IMPWSMovimiento.ImpWSMovimientoSoapPort).Execute(inValue)
            [Error] = retVal.[Error]
            Return retVal.Ok
        End Function
        
        Public Function ExecuteAsync(ByVal request As IMPWSMovimiento.ExecuteRequest) As System.Threading.Tasks.Task(Of IMPWSMovimiento.ExecuteResponse) Implements IMPWSMovimiento.ImpWSMovimientoSoapPort.ExecuteAsync
            Return MyBase.Channel.ExecuteAsync(request)
        End Function
    End Class
End Namespace
