'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.17626
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace EXPWSProveedores
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="LIBRA", ConfigurationName:="EXPWSProveedores.ExpWSProveedoresSoapPort")>  _
    Public Interface ExpWSProveedoresSoapPort
        
        <System.ServiceModel.OperationContractAttribute(Action:="LIBRAaction/AEXPWSPROVEEDORES.Execute", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function Execute(ByVal request As EXPWSProveedores.ExecuteRequest) As EXPWSProveedores.ExecuteResponse
        
        'CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        <System.ServiceModel.OperationContractAttribute(Action:="LIBRAaction/AEXPWSPROVEEDORES.Execute", ReplyAction:="*")>  _
        Function ExecuteAsync(ByVal request As EXPWSProveedores.ExecuteRequest) As System.Threading.Tasks.Task(Of EXPWSProveedores.ExecuteResponse)
    End Interface
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17626"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(TypeName:="ProveedoresSDT.ProveedorItem", [Namespace]:="LIBRA")>  _
    Partial Public Class ProveedoresSDTProveedorItem
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private codigoField As String
        
        Private nombreField As String
        
        Private razonSocialField As String
        
        Private rUTField As String
        
        Private documentoField As String
        
        Private codigoPaisField As String
        
        Private codigoDepartamentoField As String
        
        Private localidadField As String
        
        Private direccionField As String
        
        Private codigoPostalField As String
        
        Private codigoZonaField As String
        
        Private telefonosField As String
        
        Private celularField As String
        
        Private faxField As String
        
        Private email1Field As String
        
        Private email2Field As String
        
        Private webField As String
        
        Private codigoGrupoField As String
        
        Private codigoGiroField As String
        
        Private codigoOrigenField As String
        
        Private codigoPropietarioField As Short
        
        Private activoField As String
        
        Private codigoLocalField As Short
        
        Private codigoCategoriaField As String
        
        Private codigoCondicionPagoField As String
        
        Private descuento1Field As Double
        
        Private descuento2Field As Double
        
        Private descuento3Field As Double
        
        Private codigoCuentaField As String
        
        Private codigoTextoField As String
        
        '''<comentarios/>
        Public Property Codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
                Me.RaisePropertyChanged("Codigo")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
                Me.RaisePropertyChanged("Nombre")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property RazonSocial() As String
            Get
                Return Me.razonSocialField
            End Get
            Set
                Me.razonSocialField = value
                Me.RaisePropertyChanged("RazonSocial")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property RUT() As String
            Get
                Return Me.rUTField
            End Get
            Set
                Me.rUTField = value
                Me.RaisePropertyChanged("RUT")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Documento() As String
            Get
                Return Me.documentoField
            End Get
            Set
                Me.documentoField = value
                Me.RaisePropertyChanged("Documento")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CodigoPais() As String
            Get
                Return Me.codigoPaisField
            End Get
            Set
                Me.codigoPaisField = value
                Me.RaisePropertyChanged("CodigoPais")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CodigoDepartamento() As String
            Get
                Return Me.codigoDepartamentoField
            End Get
            Set
                Me.codigoDepartamentoField = value
                Me.RaisePropertyChanged("CodigoDepartamento")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Localidad() As String
            Get
                Return Me.localidadField
            End Get
            Set
                Me.localidadField = value
                Me.RaisePropertyChanged("Localidad")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Direccion() As String
            Get
                Return Me.direccionField
            End Get
            Set
                Me.direccionField = value
                Me.RaisePropertyChanged("Direccion")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CodigoPostal() As String
            Get
                Return Me.codigoPostalField
            End Get
            Set
                Me.codigoPostalField = value
                Me.RaisePropertyChanged("CodigoPostal")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CodigoZona() As String
            Get
                Return Me.codigoZonaField
            End Get
            Set
                Me.codigoZonaField = value
                Me.RaisePropertyChanged("CodigoZona")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Telefonos() As String
            Get
                Return Me.telefonosField
            End Get
            Set
                Me.telefonosField = value
                Me.RaisePropertyChanged("Telefonos")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Celular() As String
            Get
                Return Me.celularField
            End Get
            Set
                Me.celularField = value
                Me.RaisePropertyChanged("Celular")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Fax() As String
            Get
                Return Me.faxField
            End Get
            Set
                Me.faxField = value
                Me.RaisePropertyChanged("Fax")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Email1() As String
            Get
                Return Me.email1Field
            End Get
            Set
                Me.email1Field = value
                Me.RaisePropertyChanged("Email1")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Email2() As String
            Get
                Return Me.email2Field
            End Get
            Set
                Me.email2Field = value
                Me.RaisePropertyChanged("Email2")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Web() As String
            Get
                Return Me.webField
            End Get
            Set
                Me.webField = value
                Me.RaisePropertyChanged("Web")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CodigoGrupo() As String
            Get
                Return Me.codigoGrupoField
            End Get
            Set
                Me.codigoGrupoField = value
                Me.RaisePropertyChanged("CodigoGrupo")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CodigoGiro() As String
            Get
                Return Me.codigoGiroField
            End Get
            Set
                Me.codigoGiroField = value
                Me.RaisePropertyChanged("CodigoGiro")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CodigoOrigen() As String
            Get
                Return Me.codigoOrigenField
            End Get
            Set
                Me.codigoOrigenField = value
                Me.RaisePropertyChanged("CodigoOrigen")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CodigoPropietario() As Short
            Get
                Return Me.codigoPropietarioField
            End Get
            Set
                Me.codigoPropietarioField = value
                Me.RaisePropertyChanged("CodigoPropietario")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Activo() As String
            Get
                Return Me.activoField
            End Get
            Set
                Me.activoField = value
                Me.RaisePropertyChanged("Activo")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CodigoLocal() As Short
            Get
                Return Me.codigoLocalField
            End Get
            Set
                Me.codigoLocalField = value
                Me.RaisePropertyChanged("CodigoLocal")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CodigoCategoria() As String
            Get
                Return Me.codigoCategoriaField
            End Get
            Set
                Me.codigoCategoriaField = value
                Me.RaisePropertyChanged("CodigoCategoria")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CodigoCondicionPago() As String
            Get
                Return Me.codigoCondicionPagoField
            End Get
            Set
                Me.codigoCondicionPagoField = value
                Me.RaisePropertyChanged("CodigoCondicionPago")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Descuento1() As Double
            Get
                Return Me.descuento1Field
            End Get
            Set
                Me.descuento1Field = value
                Me.RaisePropertyChanged("Descuento1")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Descuento2() As Double
            Get
                Return Me.descuento2Field
            End Get
            Set
                Me.descuento2Field = value
                Me.RaisePropertyChanged("Descuento2")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Descuento3() As Double
            Get
                Return Me.descuento3Field
            End Get
            Set
                Me.descuento3Field = value
                Me.RaisePropertyChanged("Descuento3")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CodigoCuenta() As String
            Get
                Return Me.codigoCuentaField
            End Get
            Set
                Me.codigoCuentaField = value
                Me.RaisePropertyChanged("CodigoCuenta")
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CodigoTexto() As String
            Get
                Return Me.codigoTextoField
            End Get
            Set
                Me.codigoTextoField = value
                Me.RaisePropertyChanged("CodigoTexto")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ExpWSProveedores.Execute", WrapperNamespace:="LIBRA", IsWrapped:=true)>  _
    Partial Public Class ExecuteRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="LIBRA", Order:=0)>  _
        Public Empid As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="LIBRA", Order:=1)>  _
        Public Emppassword As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="LIBRA", Order:=2)>  _
        Public Codigo As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Empid As String, ByVal Emppassword As String, ByVal Codigo As String)
            MyBase.New
            Me.Empid = Empid
            Me.Emppassword = Emppassword
            Me.Codigo = Codigo
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ExpWSProveedores.ExecuteResponse", WrapperNamespace:="LIBRA", IsWrapped:=true)>  _
    Partial Public Class ExecuteResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="LIBRA", Order:=0)>  _
        Public Ok As SByte
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="LIBRA", Order:=1)>  _
        Public [Error] As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="LIBRA", Order:=2),  _
         System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Proveedores() As EXPWSProveedores.ProveedoresSDTProveedorItem
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Ok As SByte, ByVal [Error] As String, ByVal Proveedores() As EXPWSProveedores.ProveedoresSDTProveedorItem)
            MyBase.New
            Me.Ok = Ok
            Me.[Error] = [Error]
            Me.Proveedores = Proveedores
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ExpWSProveedoresSoapPortChannel
        Inherits EXPWSProveedores.ExpWSProveedoresSoapPort, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ExpWSProveedoresSoapPortClient
        Inherits System.ServiceModel.ClientBase(Of EXPWSProveedores.ExpWSProveedoresSoapPort)
        Implements EXPWSProveedores.ExpWSProveedoresSoapPort
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function EXPWSProveedores_ExpWSProveedoresSoapPort_Execute(ByVal request As EXPWSProveedores.ExecuteRequest) As EXPWSProveedores.ExecuteResponse Implements EXPWSProveedores.ExpWSProveedoresSoapPort.Execute
            Return MyBase.Channel.Execute(request)
        End Function
        
        Public Function Execute(ByVal Empid As String, ByVal Emppassword As String, ByVal Codigo As String, <System.Runtime.InteropServices.OutAttribute()> ByRef [Error] As String, <System.Runtime.InteropServices.OutAttribute()> ByRef Proveedores() As EXPWSProveedores.ProveedoresSDTProveedorItem) As SByte
            Dim inValue As EXPWSProveedores.ExecuteRequest = New EXPWSProveedores.ExecuteRequest()
            inValue.Empid = Empid
            inValue.Emppassword = Emppassword
            inValue.Codigo = Codigo
            Dim retVal As EXPWSProveedores.ExecuteResponse = CType(Me,EXPWSProveedores.ExpWSProveedoresSoapPort).Execute(inValue)
            [Error] = retVal.[Error]
            Proveedores = retVal.Proveedores
            Return retVal.Ok
        End Function
        
        Public Function ExecuteAsync(ByVal request As EXPWSProveedores.ExecuteRequest) As System.Threading.Tasks.Task(Of EXPWSProveedores.ExecuteResponse) Implements EXPWSProveedores.ExpWSProveedoresSoapPort.ExecuteAsync
            Return MyBase.Channel.ExecuteAsync(request)
        End Function
    End Class
End Namespace
